// Revisión de pre-entrega que WILLY hace DE VERDAD sobre los archivos de un proyecto (Constitución del dueño, apartados B, K,
// O, Q y R): nada a medias, ningún secreto, ningún rastro de IA innecesario, ninguna ruta de tu equipo y documentación mínima.
// No sustituye a compilar ni a probar (eso lo hacen otras comprobaciones): dice exactamente qué ha mirado y qué ha encontrado.

export type ScanKind = "a-medias" | "secreto" | "rastro-ia" | "ruta-local" | "depuracion";
export type ScanIssue = { kind: ScanKind; file: string; line: number; text: string };
export type ScanFile = { path: string; content: string };

/** Los documentos de trabajo de WILLY (docs/…) no son parte del producto: no se revisan como código. */
export const isWorkDoc = (path: string): boolean => /^docs\//i.test(path.replace(/^\.?\//, ""));

const RULES: Array<{ kind: ScanKind; re: RegExp }> = [
  // «TODO» en mayúsculas es corriente en castellano («TODO lo necesario»): solo cuenta como comentario de programador.
  { kind: "a-medias", re: /(?:\/\/|\/\*|#|<!--)\s*(?:TODO|FIXME|XXX)\b|lorem ipsum|\bresto (?:igual|del código)\b|^\s*(?:\/\/\s*)?(?:\.\.\.|…)\s*$/im },
  { kind: "secreto", re: /\bsk-(?:proj-)?[A-Za-z0-9_-]{20,}|\bAIza[0-9A-Za-z_-]{30,}|\bgsk_[A-Za-z0-9]{20,}|\bhf_[A-Za-z0-9]{20,}|\bghp_[A-Za-z0-9]{30,}|\bxox[baprs]-[A-Za-z0-9-]{10,}|\bnvapi-[A-Za-z0-9_-]{20,}|-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/ },
  { kind: "rastro-ia", re: /generated by (?:ai|chatgpt|claude|gemini)|made with ai|(?:\/\/|#|\/\*)\s*(?:ai[- ]generated|generado por (?:la )?ia|claude|chatgpt|gemini|copilot)\b|as an ai language model|como modelo de lenguaje|\bWILLY AI\b/i },
  { kind: "ruta-local", re: /\b[A-Za-z]:\\\\?Users\\\\?[^\\\s"'`]+|\/home\/[a-z][\w-]*\/|\/Users\/[A-Za-z][\w-]*\// },
  { kind: "depuracion", re: /\bdebugger;|console\.(?:log|debug)\(/ },
];

/** Revisa los archivos del producto (no los documentos de trabajo). */
export function scanDelivery(files: ScanFile[]): { checked: number; issues: ScanIssue[] } {
  const issues: ScanIssue[] = [];
  let checked = 0;
  for (const file of files) {
    if (isWorkDoc(file.path)) continue;
    checked += 1;
    const lines = file.content.split("\n");
    lines.forEach((text, i) => {
      for (const rule of RULES) {
        if (rule.re.test(text)) issues.push({ kind: rule.kind, file: file.path, line: i + 1, text: text.trim().slice(0, 140) });
      }
    });
  }
  return { checked, issues };
}

export type DocsCheck = { ok: boolean; missing: string[]; file: string | null };

/** Documentación mínima para el cliente: README con qué es, cómo instalar o arrancar, cómo usar y (si hay instalador) cómo desinstalar. */
export function checkReadme(files: ScanFile[], opts: { installer: boolean }): DocsCheck {
  const readme = files.find((f) => /^(?:\.\/)?readme(?:\.md|\.txt)?$/i.test(f.path));
  if (!readme) return { ok: false, missing: ["README (no existe)"], file: null };
  const need: Array<[string, RegExp]> = [
    ["qué es", /qu[eé] es|descripci[oó]n|acerca de|sobre (?:el|la|este)/i],
    ["cómo instalar o arrancar", /instala|arranc|puesta en marcha|c[oó]mo empezar|ejecuta/i],
    ["cómo usarlo", /\buso\b|c[oó]mo usar|manual|funciones|gu[ií]a/i],
    ...(opts.installer ? [["cómo desinstalar", /desinstal/i] as [string, RegExp]] : []),
  ];
  const missing = need.filter(([, re]) => !re.test(readme.content)).map(([label]) => label);
  return { ok: missing.length === 0, missing, file: readme.path };
}

export const SCAN_LABELS: Record<ScanKind, string> = {
  "a-medias": "algo a medias (TODO, lorem ipsum, «…»)",
  secreto: "una clave o secreto en el código",
  "rastro-ia": "un rastro de IA innecesario",
  "ruta-local": "una ruta de tu equipo",
  depuracion: "código de depuración",
};
