import { PROMPT_CARDS, type PromptCard } from "@/services/prompt-library";

// Preparan peticiones, no anuncian integraciones ni acciones que no se hayan ejecutado.
export const SUPERIA_SKILLS: PromptCard[] = [
  ...PROMPT_CARDS,
  { id: "datos", name: "Analizar datos y tablas", kind: "datos", desc: "Conclusiones, cálculos y anomalías a partir de los datos que aportes.", example: "ventas por mes", template: "DATOS Y OBJETIVO: <<pega los datos y explica qué necesitas decidir>>\nComprueba unidades y datos ausentes. Explica los cálculos reproducibles, separa observaciones e hipótesis y entrega una tabla de resultados. No inventes registros ni afirmes haber ejecutado cálculos que no has ejecutado." },
  { id: "plan", name: "Planificar un trabajo", kind: "razonamiento", desc: "Objetivo, entregables, prioridades, dependencias y comprobaciones.", example: "organizar el lanzamiento de mi negocio", template: "OBJETIVO: <<qué quieres conseguir, recursos y plazo>>\nPropón un plan por fases con entregables concretos, dependencias y criterios para comprobar cada resultado. Identifica los datos imprescindibles que faltan y distingue estimaciones de compromisos." },
  { id: "comparar", name: "Comparar opciones", kind: "razonamiento", desc: "Una decisión razonada con ventajas, costes y límites.", example: "comparar tres presupuestos", template: "OPCIONES Y CRITERIOS: <<pega las opciones y lo que más te importa>>\nEntrega una tabla comparable, explica los compromisos y recomienda una opción según los criterios indicados. No inventes precios ni características; señala lo que debe verificarse." },
  { id: "pruebas", name: "Diseñar pruebas", kind: "codigo", desc: "Casos normales, errores, accesibilidad y tamaños de pantalla.", example: "comprobar un formulario de reservas", template: "FUNCIÓN O CÓDIGO: <<describe la función o pega el código>>\nDiseña pruebas con entrada, acción y resultado esperado. Cubre los fallos relevantes y el uso desde móvil y teclado. Entrega código de prueba cuando haya contexto suficiente. Distingue pruebas propuestas de pruebas realmente ejecutadas." },
  { id: "documentar", name: "Crear una guía de uso", kind: "escritura", desc: "Instrucciones claras, ejemplos y solución de problemas.", example: "manual para los usuarios de mi aplicación", template: "PRODUCTO Y DESTINATARIO: <<qué hay que explicar, a quién y con qué información>>\nRedacta una guía ordenada por tareas con requisitos, pasos verificables y solución de errores. No describas botones ni funciones que no consten en la información aportada." },
  { id: "automatizar", name: "Preparar una automatización", kind: "codigo", desc: "Diseño y código con entradas, salidas y tratamiento de errores.", example: "organizar archivos de una carpeta", template: "PROCESO: <<qué tarea repites, entradas, salidas y entorno>>\nPropón el flujo y entrega el código cuando el entorno esté definido. Incluye validación, registro de errores y modo de prueba antes de modificar datos. No digas que está instalado, programado ni ejecutado si solo has generado el código." },
];
