// PRUEBAS AUTOMÁTICAS DE CADA PROYECTO (revisión 28) · EL «PASADOR» DE PRUEBAS. Las pruebas del proyecto (pruebas/*.spec.js,
// con el formato de Playwright) se ejecutan en un marco aislado y SIN RED (no pueden llamar a WILLY ni a internet: solo hablan
// con WILLY por mensajes). Ahí está una versión pequeña de Playwright (test, expect, page, locator…) que, en vez de mover un
// navegador, le pide a WILLY cada paso («pulsa el botón Añadir», «¿qué dice la lista?») y WILLY se lo pide al probador de la
// página (lib/test-agent). Espera sola como Playwright (hasta que aparece, se ve, se puede pulsar…) y, si algo falla, lo dice
// en castellano para cualquiera y con el detalle técnico para la IA (y la línea de la prueba).
// Es JavaScript que va dentro del marco (texto, sin comillas invertidas): se prueba en un navegador de verdad y comparándolo
// con el Playwright de verdad (cctest/rev28motor).

/** Un archivo de pruebas ya preparado (sus importaciones de @playwright/test cambiadas por lo que da WILLY). */
export type RunnerFile = { path: string; code: string; lineMap?: number[] | null };
export type RunnerConfig = { timeouts: { test: number; expect: number; action: number }; viewport: { width: number; height: number } };

export const DEFAULT_RUNNER_CONFIG: RunnerConfig = { timeouts: { test: 30_000, expect: 5_000, action: 10_000 }, viewport: { width: 1280, height: 720 } };

const RUNNER = String.raw`
"use strict";
var post=function(m){m.__willyPruebas=true;m.k=K;try{parent.postMessage(m,"*")}catch(e){}};
var now=function(){return Date.now()};
var NORM=function(s){return String(s==null?"":s).replace(/[\s\u00a0\u200b]+/g," ").trim()};
var SL=function(t,n){t=String(t==null?"":t);return t.length>n?t.slice(0,n-1)+"…":t};
var Q=function(s){return "«"+SL(s,120)+"»"};
var J=function(v){try{if(typeof v==="string")return JSON.stringify(v);if(v instanceof RegExp)return String(v);if(v===undefined)return "undefined";if(typeof v==="number"&&!isFinite(v))return String(v);return JSON.stringify(v)}catch(e){return String(v)}};
var ES=function(v){if(typeof v==="string")return Q(v);if(v instanceof RegExp)return String(v);if(v===undefined)return "nada (undefined)";if(v===null)return "null";try{return SL(JSON.stringify(v),160)}catch(e){return String(v)}};

// ------------------------------------------------------------------ hablar con WILLY
var seq=0,pending=new Map(),STOPPED=false,CUR=null;
addEventListener("message",function(e){if(e.source!==parent)return;var d=e.data;if(!d||d.__willyPruebas!==true||d.k!==K)return;
if(d.tipo==="respuesta"){var p=pending.get(d.id);if(p){pending.delete(d.id);p(d.r||{ok:false,error:"Sin respuesta"})}}
else if(d.tipo==="empezar"){runAll(d.solo||null)}
else if(d.tipo==="parar"){STOPPED=true;if(CUR)CUR.abort("parado")}
else if(d.tipo==="evento"){if(CUR)CUR.onEvent(d.evento||{})}});
var RAW=function(cmd){return new Promise(function(resolve){var id=++seq;pending.set(id,resolve);post({tipo:"orden",id:id,cmd:cmd})})};

// ------------------------------------------------------------------ fallos y en qué línea
var URLS=[];
var WHERE=function(stack){if(!stack)return null;var ls=String(stack).split("\n");for(var i=0;i<ls.length;i++){for(var j=0;j<URLS.length;j++){var u=URLS[j];if(ls[i].indexOf(u.url)<0)continue;var m=/:(\d+):(\d+)\)?\s*$/.exec(ls[i]);if(!m)continue;var ln=Number(m[1]);if(u.map&&u.map[ln-1])ln=u.map[ln-1];return {archivo:u.path,linea:ln,columna:Number(m[2])}}}return null};
var SITE=function(){try{throw new Error("sitio")}catch(e){return e.stack||""}};
function Fallo(plano,detalle,site,extra){var e=new Error(plano);e.name="Fallo";e.willy={plano:plano,detalle:detalle||plano,site:site||""};if(extra)for(var k in extra)e.willy[k]=extra[k];return e}
var NOSOP=function(what,why){return function(){throw Fallo("La prueba usa "+what+", que WILLY no puede usar en sus pruebas"+(why?": "+why:"")+".",what+" is not supported by the WILLY test runner.",SITE(),{nosoportado:true})}};

// ------------------------------------------------------------------ textos: qué se busca, en palabras
var TX=function(v){if(v instanceof RegExp)return {re:v.source,f:v.flags};return {s:String(v==null?"":v)}};
var TXS=function(t){return t&&t.re!=null?"/"+t.re+"/"+(t.f||""):String(t&&t.s)};
var TXJ=function(t){return t&&t.re!=null?"/"+t.re+"/"+(t.f||""):"'"+String(t&&t.s).replace(/'/g,"\\'")+"'"};
var ROLE_ES={button:"el botón",link:"el enlace",heading:"el título",textbox:"el campo",searchbox:"el buscador",checkbox:"la casilla",radio:"la opción",combobox:"el desplegable",listbox:"la lista de opciones",option:"la opción",list:"la lista",listitem:"el elemento de la lista",img:"la imagen",navigation:"el menú",dialog:"el diálogo",alert:"el aviso",alertdialog:"el aviso",table:"la tabla",row:"la fila",cell:"la celda",gridcell:"la celda",columnheader:"la cabecera de columna",rowheader:"la cabecera de fila",paragraph:"el párrafo",main:"el contenido principal",banner:"la cabecera",contentinfo:"el pie de página",form:"el formulario",region:"la sección",tab:"la pestaña",tabpanel:"el panel",menu:"el menú",menubar:"la barra de menú",menuitem:"la opción del menú","switch":"el interruptor",slider:"el control deslizante",spinbutton:"el campo numérico",progressbar:"la barra de progreso",status:"el mensaje de estado",article:"el artículo",group:"el grupo",separator:"el separador",figure:"la figura",complementary:"el lateral",tooltip:"la ayuda",grid:"la tabla",tree:"el árbol",treeitem:"el elemento del árbol",meter:"el indicador",log:"el registro",marquee:"el rótulo",timer:"el temporizador"};
var PRIMARY={css:1,xpath:1,role:1,text:1,label:1,placeholder:1,alt:1,title:1,testid:1};
var DSTEP=function(s){switch(s.t){case "role":return (s.role==="heading"&&s.level?"el título de nivel "+s.level:(ROLE_ES[s.role]||"el elemento con papel "+Q(s.role)))+(s.name?" "+Q(TXS(s.name)):"");
case "text":return "el texto "+Q(TXS(s.v));case "label":return "el campo "+Q(TXS(s.v));case "placeholder":return "el campo "+Q(TXS(s.v))+" (texto de ayuda)";case "alt":return "la imagen "+Q(TXS(s.v));case "title":return "el elemento con el título "+Q(TXS(s.v));case "testid":return "el elemento "+Q(TXS(s.v))+" (data-testid)";case "xpath":return Q(s.s);default:return Q(s.s)}};
var HUMAN=function(steps){var main=null,outer=null,nth=null,fl=[];for(var i=0;i<steps.length;i++){var s=steps[i];if(PRIMARY[s.t]){if(main)outer=main;main=s;nth=null;fl=[]}else if(s.t==="nth")nth=s.i;else if(s.t==="filter"){if(s.hasText)fl.push("con el texto "+Q(TXS(s.hasText)));if(s.hasNotText)fl.push("sin el texto "+Q(TXS(s.hasNotText)));if(s.has)fl.push("que contiene "+HUMAN(s.has));if(s.visible===true)fl.push("visible")}else if(s.t==="or")fl.push("(o "+HUMAN(s.loc)+")");else if(s.t==="and")fl.push("(y "+HUMAN(s.loc)+")")}
var d=main?DSTEP(main):"la página";if(fl.length)d+=" "+fl.join(", ");if(nth!==null)d+=nth===0?" (el primero)":nth===-1?" (el último)":" (el n.º "+(nth+1)+")";if(outer)d+=" dentro de "+DSTEP(outer);return d};
var TECH=function(steps){var out="";for(var i=0;i<steps.length;i++){var s=steps[i],p=out?".":"";switch(s.t){
case "css":out+=p+"locator('"+String(s.s).replace(/'/g,"\\'")+"')";break;case "xpath":out+=p+"locator('xpath="+s.s+"')";break;
case "role":{var o=[];if(s.name)o.push("name: "+TXJ(s.name));if(s.exact)o.push("exact: true");["checked","pressed","selected","expanded","disabled","level","includeHidden"].forEach(function(k){if(s[k]!=null&&s[k]!==false)o.push(k+": "+J(s[k]))});out+=p+"getByRole('"+s.role+"'"+(o.length?", { "+o.join(", ")+" }":"")+")";break}
case "text":out+=p+"getByText("+TXJ(s.v)+(s.exact?", { exact: true }":"")+")";break;case "label":out+=p+"getByLabel("+TXJ(s.v)+(s.exact?", { exact: true }":"")+")";break;case "placeholder":out+=p+"getByPlaceholder("+TXJ(s.v)+(s.exact?", { exact: true }":"")+")";break;
case "alt":out+=p+"getByAltText("+TXJ(s.v)+")";break;case "title":out+=p+"getByTitle("+TXJ(s.v)+")";break;case "testid":out+=p+"getByTestId("+TXJ(s.v)+")";break;
case "nth":out+=p+(s.i===0?"first()":s.i===-1?"last()":"nth("+s.i+")");break;
case "filter":{var f=[];if(s.hasText)f.push("hasText: "+TXJ(s.hasText));if(s.hasNotText)f.push("hasNotText: "+TXJ(s.hasNotText));if(s.has)f.push("has: "+TECH(s.has));if(s.hasNot)f.push("hasNot: "+TECH(s.hasNot));if(s.visible!=null)f.push("visible: "+s.visible);out+=p+"filter({ "+f.join(", ")+" })";break}
case "and":out+=p+"and("+TECH(s.loc)+")";break;case "or":out+=p+"or("+TECH(s.loc)+")";break}}return out||"page"};

// ------------------------------------------------------------------ selectores de Playwright (css, text=, xpath, >>, :has-text…)
var SPLITCHAIN=function(sel){var out=[],cur="",q=null,depth=0;for(var i=0;i<sel.length;i++){var c=sel[i];if(q){cur+=c;if(c==="\\"&&i+1<sel.length){cur+=sel[++i];continue}if(c===q)q=null;continue}if(c==='"'||c==="'"){q=c;cur+=c;continue}if(c==="("||c==="[")depth++;if(c===")"||c==="]")depth--;if(depth===0&&sel.substr(i,2)===">>"){out.push(cur.trim());cur="";i++;continue}cur+=c}if(cur.trim())out.push(cur.trim());return out};
var UNQ=function(s){s=s.trim();if((s[0]==='"'&&s[s.length-1]==='"')||(s[0]==="'"&&s[s.length-1]==="'"))return {v:s.slice(1,-1).replace(/\\(.)/g,"$1"),quoted:true};return {v:s,quoted:false}};
var PSEUDO=/:(has-text|text|text-is|text-matches|visible)(?:\((?:"((?:[^"\\]|\\.)*)"|'((?:[^'\\]|\\.)*)'|([^)]*))\))?$/;
var PARSESEL=function(sel){var steps=[];var parts=SPLITCHAIN(String(sel));for(var i=0;i<parts.length;i++){var p=parts[i];var m;
if(/^text\s*=/.test(p)){var u=UNQ(p.replace(/^text\s*=\s*/,""));var rx=/^\/(.*)\/([a-z]*)$/.exec(u.v);steps.push(rx&&!u.quoted?{t:"text",v:{re:rx[1],f:rx[2]}}:{t:"text",v:{s:u.v},exact:u.quoted});continue}
if(/^xpath\s*=/.test(p)||/^\.?\/\//.test(p)||/^\.\.$/.test(p)){steps.push({t:"xpath",s:p.replace(/^xpath\s*=\s*/,"")});continue}
if(/^nth\s*=/.test(p)){steps.push({t:"nth",i:Number(p.replace(/^nth\s*=\s*/,""))||0});continue}
if(/^internal:/.test(p))throw Fallo("La prueba usa un selector interno de Playwright ("+SL(p,60)+"): usa getByRole, getByText, getByLabel…","Unsupported selector: "+p,SITE());
if((m=/^role\s*=\s*([a-z]+)(.*)$/.exec(p))){var st={t:"role",role:m[1]};var ra=m[2].match(/\[[^\]]+\]/g)||[];ra.forEach(function(a){var mm=/^\[\s*([a-z-]+)\s*(?:=\s*(.*?))?\s*\]$/.exec(a);if(!mm)return;var val=mm[2]==null?true:UNQ(mm[2].replace(/[is]$/,"")).v;if(mm[1]==="name"){st.name={s:String(val)};if(/s$/.test(mm[2]||""))st.exact=true}else if(mm[1]==="level")st.level=Number(val);else if(mm[1]==="include-hidden")st.includeHidden=val!=="false";else st[mm[1]]=val==="true"||val===true});steps.push(st);continue}
if(/^css\s*=/.test(p))p=p.replace(/^css\s*=\s*/,"");
var filters=[];while((m=PSEUDO.exec(p))){var arg=m[2]!=null?m[2].replace(/\\(.)/g,"$1"):m[3]!=null?m[3].replace(/\\(.)/g,"$1"):m[4]!=null?m[4].trim():"";var kind=m[1];p=p.slice(0,m.index);
if(kind==="visible")filters.unshift({t:"filter",visible:true});else if(kind==="has-text")filters.unshift({t:"filter",hasText:{s:arg}});else if(kind==="text-matches"){var rr=/^\/(.*)\/([a-z]*)$/.exec(arg);filters.unshift({t:"filter",hasText:rr?{re:rr[1],f:rr[2]}:{re:arg,f:""}})}else filters.unshift({t:"filter",hasText:{s:arg},textIs:kind==="text-is"})}
steps.push({t:"css",s:p.trim()||"*"});for(var f=0;f<filters.length;f++){var fl=filters[f];if(fl.textIs){steps.push({t:"filter",hasText:{re:"^\\s*"+String(fl.hasText.s).replace(/[.*+?^$()|[\]{}\\]/g,"\\$&")+"\\s*$",f:""}})}else steps.push(fl)}}
return steps};

// ------------------------------------------------------------------ la prueba en marcha
function Ctx(t){this.gen=0;this.t=t;this.steps=[];this.soft=[];this.pageErrors=[];this.dialogs=[];this.aborted=null;this.page=null;this.started=now();this.timeout=t.timeoutMs;this.deadline=this.started+this.timeout;this.handlers={dialog:[],console:[],pageerror:[]};this.lastPost=0;this.extra=null}
Ctx.prototype.abort=function(why){this.aborted=why};
Ctx.prototype.check=function(g){if(this.aborted==="parado")throw Fallo("Pruebas paradas.","Stopped.",null,{parado:true});if(this.aborted)throw Fallo("La prueba se ha parado ("+this.aborted+").","Aborted: "+this.aborted,null,{tiempo:true});if(g!=null&&g!==this.gen)throw Fallo("(cancelada)","cancelled",null,{cancelada:true})};
Ctx.prototype.sleep=function(ms){var self=this,g=this.gen;return new Promise(function(r){setTimeout(r,ms)}).then(function(){self.check(g)})};
Ctx.prototype.cmd=async function(cmd){var g=this.gen;this.check(g);var r=await RAW(cmd);this.check(g);if(r&&r.url&&this.page)this.page._lastUrl=r.url;return r};
Ctx.prototype.step=function(text){this.steps.push(text);if(this.steps.length>40)this.steps.shift();var n=now();if(n-this.lastPost>120){this.lastPost=n;post({tipo:"paso",id:this.t.id,texto:SL(text,160)})}};
Ctx.prototype.remaining=function(){return Math.max(0,this.deadline-now())};
Ctx.prototype.actionTimeout=function(){return Math.max(200,Math.min(CFG.timeouts.action,this.remaining()))};
Ctx.prototype.expectTimeout=function(){return Math.max(200,Math.min(CFG.timeouts.expect,this.remaining()))};
Ctx.prototype.onEvent=function(ev){var self=this;if(ev.clase==="error"){this.pageErrors.push(SL(ev.mensaje,400));this.handlers.pageerror.forEach(function(h){try{var er=new Error(ev.mensaje);h(er)}catch(e){}})}
else if(ev.clase==="consola"){this.handlers.console.forEach(function(h){try{h({type:function(){return ev.nivel==="warn"?"warning":ev.nivel},text:function(){return ev.texto},args:function(){return []},location:function(){return {}}})}catch(e){}})}
else if(ev.clase==="dialogo"){this.dialogs.push(ev.tipo+": "+ev.mensaje);this.handlers.dialog.forEach(function(h){try{var r=h(new Dialog(ev,true));if(r&&r.catch)r.catch(function(){})}catch(e){}})}};

// ------------------------------------------------------------------ avisos de la página (dialog)
function Dialog(ev,decided){this._ev=ev||{};this._decided=!!decided;this.decision=null;this.text=null}
Dialog.prototype.type=function(){return this._ev.tipo||"confirm"};Dialog.prototype.message=function(){return this._ev.mensaje||""};Dialog.prototype.defaultValue=function(){return ""};
Dialog.prototype.accept=async function(t){this.decision="aceptar";this.text=t==null?null:String(t)};Dialog.prototype.dismiss=async function(){this.decision="rechazar"};Dialog.prototype.page=function(){return CUR&&CUR.page};

// ------------------------------------------------------------------ Page
function Page(ctx,use){this._ctx=ctx;this._use=use||{};this._opened=false;this._vp=use&&use.viewport||CFG.viewport;this.keyboard=new Keyboard(this);this.mouse=new Mouse(this);this.touchscreen={tap:NOSOP("page.touchscreen")};this._ctxObj=null}
Page.prototype._ensure=async function(){if(!this._opened)await this.goto("/")};
Page.prototype._q=async function(cmd,what,site){var r=await this._ctx.cmd(cmd);if(!r.ok)throw Fallo((what||"La página")+": "+(r.error||r.motivo||"no contesta"),(what||"page")+": "+(r.error||r.motivo),site);return r.value};
Page.prototype.goto=async function(url,opts){var site=SITE();this._ctx.step("Abrir "+Q(String(url)));var r=await this._ctx.cmd({op:"abrir",url:String(url==null?"/":url)});if(!r.ok)throw Fallo("No he podido abrir "+Q(String(url))+": "+r.error,"page.goto: "+r.error,site);this._opened=true;this._lastUrl=r.value&&r.value.url||this._lastUrl;return new Response(r.value&&r.value.url)};
Page.prototype.reload=async function(){var site=SITE();this._ctx.step("Recargar la página");await this._ensure();var r=await this._ctx.cmd({op:"recargar"});if(!r.ok)throw Fallo("No he podido recargar la página: "+r.error,"page.reload: "+r.error,site);return new Response(r.value&&r.value.url)};
Page.prototype.goBack=async function(){this._ctx.step("Volver atrás");await this._ensure();await this._ctx.cmd({op:"historia",que:"atras"});await this._ctx.sleep(80);return null};
Page.prototype.goForward=async function(){this._ctx.step("Ir adelante");await this._ensure();await this._ctx.cmd({op:"historia",que:"adelante"});await this._ctx.sleep(80);return null};
Page.prototype._info=async function(){var r=await this._ctx.cmd({op:"url"});if(!r.ok)throw Fallo("La página no contesta: "+r.error,"page.url: "+r.error,SITE());return r.value};
Page.prototype.url=function(){return this._lastUrl||"about:blank"};
Page.prototype.title=async function(){await this._ensure();var v=await this._info();this._lastUrl=v.url;return v.title};
Page.prototype.content=async function(){await this._ensure();return this._q({op:"html"},"page.content")};
Page.prototype.setViewportSize=async function(s){this._ctx.step("Cambiar el tamaño a "+s.width+"\u00d7"+s.height);this._vp={width:Number(s.width)||1280,height:Number(s.height)||720};await this._ctx.cmd({op:"tamano",width:this._vp.width,height:this._vp.height})};
Page.prototype.viewportSize=function(){return this._vp};
Page.prototype.waitForTimeout=async function(ms){this._ctx.step("Esperar "+ms+" ms");await this._ctx.sleep(Math.min(Number(ms)||0,this._ctx.remaining()))};
Page.prototype.waitForLoadState=async function(){await this._ensure();await this._info()};
Page.prototype.waitForURL=async function(u,o){var site=SITE();o=o||{};await this._ensure();var to=o.timeout!=null&&o.timeout>0?o.timeout:this._ctx.actionTimeout(),dl=now()+to,last="";for(var i=0;;i++){var v=await this._info();last=v.url;this._lastUrl=v.url;if(URLOK(u,v.url))return;if(now()>=dl)break;await this._ctx.sleep(i<10?50:100)}throw Fallo("La página no ha llegado a "+Q(u instanceof RegExp?String(u):u)+" (está en "+Q(last)+").","page.waitForURL: Timeout "+to+"ms exceeded.\nExpected: "+J(u)+"\nReceived: "+J(last),site)};
Page.prototype.waitForSelector=async function(sel,o){var l=this.locator(sel);await l.waitFor({state:o&&o.state||"visible",timeout:o&&o.timeout});return null};
Page.prototype.waitForFunction=async function(fn,arg,o){var site=SITE();o=o||{};await this._ensure();var to=o.timeout!=null&&o.timeout>0?o.timeout:this._ctx.actionTimeout(),dl=now()+to;for(var i=0;;i++){var r=await this._ctx.cmd({op:"evaluar",fn:String(fn),esFn:typeof fn==="function",arg:ENC(arg)});if(r.ok&&DEC(r.value))return DEC(r.value);if(!r.ok&&r.enPagina===false)break;if(now()>=dl)break;await this._ctx.sleep(o.polling>0?o.polling:100)}throw Fallo("La condición de la prueba no se ha cumplido en "+Math.round(to/1000)+" s.","page.waitForFunction: Timeout "+to+"ms exceeded.",site)};
Page.prototype.evaluate=async function(fn,arg){var site=SITE();await this._ensure();var r=await this._ctx.cmd({op:"evaluar",fn:String(fn),esFn:typeof fn==="function",arg:ENC(arg)});if(!r.ok)throw Fallo("El código de la prueba ha fallado dentro de la página: "+(r.error||r.motivo),"page.evaluate: "+(r.error||r.motivo),site);return DEC(r.value)};
Page.prototype.evaluateHandle=NOSOP("page.evaluateHandle");Page.prototype.$=NOSOP("page.$()","usa page.locator()");Page.prototype.$$=NOSOP("page.$$()","usa page.locator()");Page.prototype.$eval=NOSOP("page.$eval()","usa page.locator(...).evaluate()");Page.prototype.$$eval=NOSOP("page.$$eval()","usa page.locator(...).evaluateAll()");
Page.prototype.route=NOSOP("page.route()","las pruebas no cambian la red");Page.prototype.unroute=async function(){};Page.prototype.frameLocator=NOSOP("frameLocator()");Page.prototype.frame=function(){return null};Page.prototype.frames=function(){return []};Page.prototype.mainFrame=function(){return this};
Page.prototype.waitForResponse=NOSOP("page.waitForResponse()","las pruebas no ven la red");Page.prototype.waitForRequest=NOSOP("page.waitForRequest()","las pruebas no ven la red");Page.prototype.waitForEvent=NOSOP("page.waitForEvent()");Page.prototype.exposeFunction=NOSOP("page.exposeFunction()");Page.prototype.addInitScript=NOSOP("page.addInitScript()");
Page.prototype.screenshot=async function(){return new Uint8Array(0)};Page.prototype.pdf=async function(){return new Uint8Array(0)};Page.prototype.pause=async function(){};Page.prototype.close=async function(){};Page.prototype.isClosed=function(){return false};Page.prototype.bringToFront=async function(){};Page.prototype.emulateMedia=async function(){};Page.prototype.setExtraHTTPHeaders=async function(){};Page.prototype.setDefaultTimeout=function(ms){CFG.timeouts.action=Number(ms)||CFG.timeouts.action};Page.prototype.setDefaultNavigationTimeout=function(){};
Page.prototype.context=function(){if(!this._ctxObj)this._ctxObj=new BrowserContext(this);return this._ctxObj};
Page.prototype.on=function(ev,h){var hs=this._ctx.handlers[ev];if(!hs)return this;hs.push(h);if(ev==="dialog")this._setDialog(h);return this};Page.prototype.once=Page.prototype.on;Page.prototype.addListener=Page.prototype.on;
Page.prototype.off=function(ev,h){var hs=this._ctx.handlers[ev];if(hs){var i=hs.indexOf(h);if(i>=0)hs.splice(i,1)}if(ev==="dialog"&&!this._ctx.handlers.dialog.length)this._ctx.cmd({op:"dialogo",politica:"rechazar"}).catch(function(){});return this};Page.prototype.removeListener=Page.prototype.off;
Page.prototype._setDialog=function(h){var d=new Dialog({tipo:"confirm",mensaje:""},false);try{var r=h(d);if(r&&r.catch)r.catch(function(){})}catch(e){}var pol=d.decision||"aceptar";this._ctx.cmd({op:"dialogo",politica:pol,texto:d.text}).catch(function(){})};
Page.prototype.locator=function(sel,o){return new Locator(this,[]).locator(sel,o)};
["getByRole","getByText","getByLabel","getByPlaceholder","getByAltText","getByTitle","getByTestId"].forEach(function(n){Page.prototype[n]=function(a,b){return new Locator(this,[])[n](a,b)}});
[["click","click"],["dblclick","dblclick"],["tap","tap"],["hover","hover"],["focus","focus"],["check","check"],["uncheck","uncheck"],["textContent","textContent"],["innerText","innerText"],["innerHTML","innerHTML"],["inputValue","inputValue"],["isVisible","isVisible"],["isHidden","isHidden"],["isEnabled","isEnabled"],["isDisabled","isDisabled"],["isChecked","isChecked"],["isEditable","isEditable"]].forEach(function(p){Page.prototype[p[0]]=function(sel,o){return this.locator(sel)[p[1]](o)}});
Page.prototype.fill=function(sel,v,o){return this.locator(sel).fill(v,o)};Page.prototype.type=function(sel,v,o){return this.locator(sel).pressSequentially(v,o)};Page.prototype.press=function(sel,k,o){return this.locator(sel).press(k,o)};Page.prototype.selectOption=function(sel,v,o){return this.locator(sel).selectOption(v,o)};Page.prototype.getAttribute=function(sel,n,o){return this.locator(sel).getAttribute(n,o)};Page.prototype.dispatchEvent=function(sel,t,i,o){return this.locator(sel).dispatchEvent(t,i,o)};Page.prototype.setInputFiles=NOSOP("setInputFiles()","las pruebas no suben archivos");
function Response(u){this._u=u||""}Response.prototype.ok=function(){return true};Response.prototype.status=function(){return 200};Response.prototype.url=function(){return this._u};Response.prototype.text=async function(){return ""};Response.prototype.json=async function(){return null};Response.prototype.headers=function(){return {}};
function BrowserContext(page){this._page=page}BrowserContext.prototype.pages=function(){return [this._page]};BrowserContext.prototype.newPage=NOSOP("context.newPage()","cada prueba tiene una sola página");BrowserContext.prototype.close=async function(){};BrowserContext.prototype.clearCookies=async function(){};BrowserContext.prototype.addCookies=async function(){};BrowserContext.prototype.cookies=async function(){return []};BrowserContext.prototype.grantPermissions=async function(){};BrowserContext.prototype.clearPermissions=async function(){};BrowserContext.prototype.setOffline=async function(){};BrowserContext.prototype.storageState=async function(){return {cookies:[],origins:[]}};BrowserContext.prototype.route=NOSOP("context.route()","las pruebas no cambian la red");BrowserContext.prototype.addInitScript=NOSOP("context.addInitScript()");BrowserContext.prototype.on=function(){return this};BrowserContext.prototype.waitForEvent=NOSOP("context.waitForEvent()");BrowserContext.prototype.setDefaultTimeout=function(){};
function Keyboard(page){this._p=page}
Keyboard.prototype.press=async function(k){this._p._ctx.step("Pulsar la tecla "+k);await this._p._ensure();await this._p._q({op:"teclado",que:"press",tecla:String(k)},"keyboard.press")};
Keyboard.prototype.type=async function(t){this._p._ctx.step("Escribir "+Q(t));await this._p._ensure();await this._p._q({op:"teclado",que:"type",texto:String(t)},"keyboard.type")};
Keyboard.prototype.insertText=async function(t){await this._p._ensure();await this._p._q({op:"teclado",que:"insertText",texto:String(t)},"keyboard.insertText")};
Keyboard.prototype.down=async function(k){await this._p._ensure();await this._p._q({op:"teclado",que:"down",tecla:String(k)},"keyboard.down")};Keyboard.prototype.up=async function(k){await this._p._ensure();await this._p._q({op:"teclado",que:"up",tecla:String(k)},"keyboard.up")};
function Mouse(page){this._p=page}
Mouse.prototype.click=async function(x,y,o){this._p._ctx.step("Pulsar en ("+x+", "+y+")");await this._p._ensure();await this._p._q({op:"raton",que:"click",x:x,y:y,boton:o&&o.button,clickCount:o&&o.clickCount},"mouse.click")};
Mouse.prototype.dblclick=async function(x,y){await this._p._ensure();await this._p._q({op:"raton",que:"dblclick",x:x,y:y},"mouse.dblclick")};Mouse.prototype.move=async function(x,y){this._x=x;this._y=y;await this._p._ensure();await this._p._q({op:"raton",que:"move",x:x,y:y},"mouse.move")};
Mouse.prototype.down=async function(){await this._p._ensure();await this._p._q({op:"raton",que:"down",x:this._x||0,y:this._y||0},"mouse.down")};Mouse.prototype.up=async function(){await this._p._ensure();await this._p._q({op:"raton",que:"up",x:this._x||0,y:this._y||0},"mouse.up")};
Mouse.prototype.wheel=async function(dx,dy){await this._p._ensure();await this._p._q({op:"raton",que:"wheel",x:this._x||10,y:this._y||10,dx:dx,dy:dy},"mouse.wheel")};

// ------------------------------------------------------------------ valores que van y vienen de la página
var ENC=function(v,d){d=d||0;if(v===undefined)return {__u:1};if(v===null||typeof v==="boolean"||typeof v==="string")return v;if(typeof v==="number"){if(isNaN(v))return {__n:"NaN"};if(!isFinite(v))return {__n:v>0?"Infinity":"-Infinity"};return v}if(d>8)return null;if(v instanceof Date)return {__d:v.toISOString()};if(v instanceof RegExp)return {__r:v.source,f:v.flags};if(Array.isArray(v))return v.map(function(x){return ENC(x,d+1)});if(typeof v==="object"){var o={};Object.keys(v).forEach(function(k){o[k]=ENC(v[k],d+1)});return o}return null};
var DEC=function(v){if(v&&typeof v==="object"){if(v.__u)return undefined;if(v.__n!=null)return v.__n==="-0"?-0:Number(v.__n);if(v.__d)return new Date(v.__d);if(v.__r!=null)return new RegExp(v.__r,v.f||"");if(v.__b!=null)return v.__b;if(v.__e!=null)return v.__e;if(v.__m)return new Map(v.__m.map(function(p){return [DEC(p[0]),DEC(p[1])]}));if(v.__s)return new Set(v.__s.map(DEC));if(Array.isArray(v))return v.map(DEC);var o={};for(var k in v)o[k]=DEC(v[k]);return o}return v};
var URLOK=function(exp,url){if(exp instanceof RegExp){exp.lastIndex=0;return exp.test(url)}if(typeof exp==="function"){try{return !!exp(new URL(url))}catch(e){return false}}var a=String(exp==null?"":exp);var clean=function(u){u=String(u).replace(/^[a-z][a-z0-9+.-]*:\/\/[^/#?]*/i,"");if(!u||u[0]==="#")u="/"+u;u=u.replace(/^\/(?:index\.html?)(?=$|[#?])/i,"/");u=u.replace(/^\/+/,"/");if(u.length>1)u=u.replace(/\/(?=$|#)/,"");return u};return clean(a)===clean(url)||(a.indexOf("*")>=0&&new RegExp("^"+a.replace(/[.+?^$()|[\]{}\\]/g,"\\$&").replace(/\*\*/g,"\u0001").replace(/\*/g,"[^/]*").replace(/\u0001/g,".*")+"$").test(url))};

// ------------------------------------------------------------------ Locator
function Locator(page,steps){this._p=page;this._s=steps}
Locator.prototype.toString=function(){return TECH(this._s)};
Locator.prototype._w=function(st){return new Locator(this._p,this._s.concat([st]))};
Locator.prototype._opts=function(o){if(!o)return this;var f={t:"filter"},any=false;if(o.hasText!=null){f.hasText=TX(o.hasText);any=true}if(o.hasNotText!=null){f.hasNotText=TX(o.hasNotText);any=true}if(o.has){f.has=o.has._s;any=true}if(o.hasNot){f.hasNot=o.hasNot._s;any=true}if(o.visible!=null){f.visible=!!o.visible;any=true}return any?this._w(f):this};
Locator.prototype.locator=function(sel,o){var base=sel instanceof Locator?new Locator(this._p,this._s.concat(sel._s)):new Locator(this._p,this._s.concat(PARSESEL(sel)));return base._opts(o)};
Locator.prototype.getByRole=function(role,o){o=o||{};var st={t:"role",role:String(role)};if(o.name!=null)st.name=TX(o.name);if(o.exact)st.exact=true;["checked","pressed","selected","expanded","disabled","includeHidden"].forEach(function(k){if(o[k]!=null)st[k]=o[k]});if(o.level)st.level=Number(o.level);return this._w(st)};
Locator.prototype.getByText=function(t,o){return this._w({t:"text",v:TX(t),exact:!!(o&&o.exact)})};
Locator.prototype.getByLabel=function(t,o){return this._w({t:"label",v:TX(t),exact:!!(o&&o.exact)})};
Locator.prototype.getByPlaceholder=function(t,o){return this._w({t:"placeholder",v:TX(t),exact:!!(o&&o.exact)})};
Locator.prototype.getByAltText=function(t,o){return this._w({t:"alt",v:TX(t),exact:!!(o&&o.exact)})};
Locator.prototype.getByTitle=function(t,o){return this._w({t:"title",v:TX(t),exact:!!(o&&o.exact)})};
Locator.prototype.getByTestId=function(t){return this._w({t:"testid",v:TX(t)})};
Locator.prototype.first=function(){return this._w({t:"nth",i:0})};Locator.prototype.last=function(){return this._w({t:"nth",i:-1})};Locator.prototype.nth=function(i){return this._w({t:"nth",i:Number(i)||0})};
Locator.prototype.filter=function(o){return this._opts(o)};Locator.prototype.and=function(l){return this._w({t:"and",loc:l._s})};Locator.prototype.or=function(l){return this._w({t:"or",loc:l._s})};
Locator.prototype.page=function(){return this._p};Locator.prototype.contentFrame=NOSOP("contentFrame()");Locator.prototype.frameLocator=NOSOP("frameLocator()");Locator.prototype.elementHandle=NOSOP("elementHandle()","usa el locator directamente");Locator.prototype.elementHandles=NOSOP("elementHandles()","usa el locator directamente");Locator.prototype.screenshot=async function(){return new Uint8Array(0)};Locator.prototype.highlight=async function(){};Locator.prototype.setInputFiles=NOSOP("setInputFiles()","las pruebas no suben archivos");Locator.prototype.dragTo=NOSOP("dragTo()");Locator.prototype.describe=function(){return this};
var ACTVERB={click:"pulsar",dblclick:"pulsar dos veces",tap:"tocar",hover:"pasar por encima de",fill:"escribir en",clear:"vaciar",type:"escribir en",press:"pulsar una tecla en",focus:"poner el foco en",blur:"quitar el foco de",scroll:"llegar a",check:"marcar",select:"elegir en",dispatch:"lanzar un evento en"};
var REASON=function(r){switch(r.motivo){case "no-existe":return ["no aparece en la página","waiting for locator to be visible"];case "varios":return ["hay "+r.n+" que coinciden y no sé cuál (hay que concretar más la prueba)","strict mode violation: resolved to "+r.n+" elements:\n"+(r.muestras||[]).map(function(m,i){return "    "+(i+1)+") "+m}).join("\n")];
case "oculto":return ["está en la página pero no se ve","element is not visible"];case "desactivado":return ["está desactivado","element is not enabled"];case "no-editable":return ["no se puede escribir en él","element is not editable"];
case "tapado":return ["lo tapa otro elemento ("+SL(r.por||"",120)+")",SL(r.por||"",200)+" intercepts pointer events"];case "fuera":return ["está fuera de la pantalla","element is outside of the viewport"];
case "no-rellenable":return ["no es un campo de texto (es de tipo "+Q(r.tipo)+")","Input of type \""+r.tipo+"\" cannot be filled"];case "no-numero":return ["es un campo de números y el texto no es un número","Cannot type text into input[type=number]"];case "es-lista":return ["es una lista desplegable: se elige con selectOption","Element is a <select>, use selectOption"];
case "no-es-casilla":return ["no es una casilla","Not a checkbox or radio button"];case "radio-no-se-desmarca":return ["una opción redonda (radio) no se puede desmarcar","Cannot uncheck radio button"];case "no-cambia":return ["al pulsarla no cambia","Clicking the checkbox did not change its state"];
case "no-es-lista":return ["no es una lista desplegable","Element is not a <select> element"];case "sin-opcion":return ["no tiene la opción "+Q(r.opcion),"did not find some options: "+r.opcion];default:return [r.error||r.motivo||"no responde",r.error||r.motivo||"failed"]}};
Locator.prototype._act=async function(que,extra,o,site,label){o=o||{};var ctx=this._p._ctx;ctx.step(label);await this._p._ensure();var to=o.timeout!=null&&o.timeout>0?o.timeout:ctx.actionTimeout();var dl=now()+to,last=null;
for(var i=0;;i++){var cmd={op:"accion",loc:this._s,que:que,opciones:{force:!!o.force,position:o.position||null,button:o.button||"left",clickCount:o.clickCount||1,modifiers:o.modifiers||[]}};if(extra)for(var k in extra)cmd[k]=extra[k];
var r=await ctx.cmd(cmd);if(r.ok)return r.value;last=r;if(r.error&&!r.motivo)throw Fallo("No he podido "+ACTVERB[que]+" "+HUMAN(this._s)+": "+r.error,"locator."+que+": "+r.error+"\nLocator: "+TECH(this._s),site);if(!r.reintentar||now()>=dl)break;await ctx.sleep(i<10?50:150)}
var why=REASON(last||{});throw Fallo("No he podido "+ACTVERB[que]+" "+HUMAN(this._s)+": "+why[0]+".","locator."+(que==="select"?"selectOption":que==="type"?"pressSequentially":que)+": "+(last&&last.reintentar?"Timeout "+to+"ms exceeded.\n":"")+"Locator: "+TECH(this._s)+"\n  - "+why[1],site,{motivo:last&&last.motivo})};
Locator.prototype.click=function(o){return this._act("click",null,o,SITE(),"Pulsar "+HUMAN(this._s))};
Locator.prototype.dblclick=function(o){return this._act("dblclick",null,o,SITE(),"Pulsar dos veces "+HUMAN(this._s))};
Locator.prototype.tap=function(o){return this._act("tap",null,o,SITE(),"Tocar "+HUMAN(this._s))};
Locator.prototype.hover=function(o){return this._act("hover",null,o,SITE(),"Pasar por encima de "+HUMAN(this._s))};
Locator.prototype.fill=function(v,o){return this._act("fill",{valor:String(v==null?"":v)},o,SITE(),"Escribir "+Q(String(v))+" en "+HUMAN(this._s))};
Locator.prototype.clear=function(o){return this._act("clear",null,o,SITE(),"Vaciar "+HUMAN(this._s))};
Locator.prototype.pressSequentially=function(v,o){return this._act("type",{valor:String(v==null?"":v)},o,SITE(),"Escribir "+Q(String(v))+" en "+HUMAN(this._s))};Locator.prototype.type=Locator.prototype.pressSequentially;
Locator.prototype.press=function(k,o){return this._act("press",{valor:String(k)},o,SITE(),"Pulsar la tecla "+k+" en "+HUMAN(this._s))};
Locator.prototype.focus=function(o){return this._act("focus",null,o,SITE(),"Poner el foco en "+HUMAN(this._s))};Locator.prototype.blur=function(o){return this._act("blur",null,o,SITE(),"Quitar el foco de "+HUMAN(this._s))};
Locator.prototype.scrollIntoViewIfNeeded=function(o){return this._act("scroll",null,o,SITE(),"Llegar hasta "+HUMAN(this._s))};
Locator.prototype.check=function(o){return this._act("check",{valor:true},o,SITE(),"Marcar "+HUMAN(this._s))};Locator.prototype.uncheck=function(o){return this._act("check",{valor:false},o,SITE(),"Desmarcar "+HUMAN(this._s))};
Locator.prototype.setChecked=function(b,o){return this._act("check",{valor:!!b},o,SITE(),(b?"Marcar ":"Desmarcar ")+HUMAN(this._s))};
Locator.prototype.selectOption=function(v,o){var list=(Array.isArray(v)?v:[v]).map(function(x){if(x&&typeof x==="object")return {value:x.value!=null?String(x.value):null,label:x.label!=null?String(x.label):null,index:x.index!=null?Number(x.index):null};return {any:String(x)}});return this._act("select",{valor:list},o,SITE(),"Elegir "+(Array.isArray(v)?v.map(function(x){return Q(typeof x==="object"?x.label||x.value:x)}).join(", "):Q(typeof v==="object"?v.label||v.value:v))+" en "+HUMAN(this._s))};
Locator.prototype.dispatchEvent=function(t,init,o){return this._act("dispatch",{valor:String(t),init:init||{}},o,SITE(),"Lanzar "+Q(t)+" en "+HUMAN(this._s))};
Locator.prototype._one=async function(campos,what,o,extra){var site=SITE(),ctx=this._p._ctx;await this._p._ensure();var to=o&&o.timeout>0?o.timeout:ctx.actionTimeout(),dl=now()+to;for(var i=0;;i++){var r=await ctx.cmd({op:"estado",loc:this._s,campos:campos,attrs:extra&&extra.attrs,max:2});if(!r.ok)throw Fallo(r.error,r.error,site);var v=r.value;if(v.n>1)throw Fallo("No he podido leer "+HUMAN(this._s)+": hay "+v.n+" que coinciden y no sé cuál.","locator."+what+": strict mode violation: "+TECH(this._s)+" resolved to "+v.n+" elements",site);if(v.n===1)return v.items[0];if(now()>=dl)break;await ctx.sleep(i<10?50:150)}throw Fallo("No he podido leer "+HUMAN(this._s)+": no aparece en la página.","locator."+what+": Timeout "+to+"ms exceeded.\nLocator: "+TECH(this._s),site)};
Locator.prototype._peek=async function(campos,what){var site=SITE(),ctx=this._p._ctx;await this._p._ensure();var r=await ctx.cmd({op:"estado",loc:this._s,campos:campos,max:2});if(!r.ok)throw Fallo(r.error,r.error,site);var v=r.value;if(v.n>1)throw Fallo("No he podido mirar "+HUMAN(this._s)+": hay "+v.n+" que coinciden y no sé cuál.","locator."+what+": strict mode violation: "+TECH(this._s)+" resolved to "+v.n+" elements",site);return v.n?v.items[0]:null};
Locator.prototype.textContent=async function(o){return (await this._one(["txt"],"textContent",o)).txt};
Locator.prototype.innerText=async function(o){return (await this._one(["inner"],"innerText",o)).inner};
Locator.prototype.innerHTML=async function(o){await this._one(["txt"],"innerHTML",o);return this.evaluate(function(el){return el.innerHTML})};
Locator.prototype.inputValue=async function(o){var s=await this._one(["val"],"inputValue",o);if(s.val==null)throw Fallo("No he podido leer el valor de "+HUMAN(this._s)+": no es un campo.","locator.inputValue: Error: Node is not an <input>, <textarea> or <select> element",SITE());return s.val};
Locator.prototype.getAttribute=async function(n,o){var s=await this._one([],"getAttribute",o,{attrs:[String(n)]});return s.attrs[String(n)]};
Locator.prototype.isVisible=async function(){var s=await this._peek(["vis"],"isVisible");return !!(s&&s.vis)};Locator.prototype.isHidden=async function(){var s=await this._peek(["vis"],"isHidden");return !(s&&s.vis)};
Locator.prototype.isEnabled=async function(o){return !!(await this._one(["en"],"isEnabled",o)).en};Locator.prototype.isDisabled=async function(o){return !(await this._one(["en"],"isDisabled",o)).en};
Locator.prototype.isEditable=async function(o){return !!(await this._one(["ed"],"isEditable",o)).ed};
Locator.prototype.isChecked=async function(o){var s=await this._one(["chk"],"isChecked",o);if(s.chk===null)throw Fallo("No he podido mirar si "+HUMAN(this._s)+" está marcada: no es una casilla.","locator.isChecked: Error: Not a checkbox or radio button",SITE());return s.chk===true};
Locator.prototype.boundingBox=async function(){var s=await this._peek(["box","vis"],"boundingBox");return s&&s.vis?s.box:null};
Locator.prototype.count=async function(){await this._p._ensure();var r=await this._p._ctx.cmd({op:"contar",loc:this._s});if(!r.ok)throw Fallo(r.error,r.error,SITE());return r.value};
Locator.prototype.all=async function(){var n=await this.count(),out=[];for(var i=0;i<n;i++)out.push(this.nth(i));return out};
Locator.prototype.allTextContents=async function(){await this._p._ensure();var r=await this._p._ctx.cmd({op:"estado",loc:this._s,campos:["txt"],max:500});if(!r.ok)throw Fallo(r.error,r.error,SITE());return r.value.items.map(function(x){return x.txt})};
Locator.prototype.allInnerTexts=async function(){await this._p._ensure();var r=await this._p._ctx.cmd({op:"estado",loc:this._s,campos:["inner"],max:500});if(!r.ok)throw Fallo(r.error,r.error,SITE());return r.value.items.map(function(x){return x.inner})};
Locator.prototype.evaluate=async function(fn,arg,o){var site=SITE(),ctx=this._p._ctx;await this._p._ensure();var to=o&&o.timeout>0?o.timeout:ctx.actionTimeout(),dl=now()+to,last;for(var i=0;;i++){var r=await ctx.cmd({op:"evaluar",fn:String(fn),esFn:true,arg:ENC(arg),loc:this._s});if(r.ok)return DEC(r.value);last=r;if(!r.reintentar||now()>=dl)break;await ctx.sleep(i<10?50:150)}var why=REASON(last||{});throw Fallo("No he podido ejecutar el código de la prueba sobre "+HUMAN(this._s)+": "+(last&&last.error||why[0])+".","locator.evaluate: "+(last&&last.error||why[1]),site)};
Locator.prototype.evaluateAll=async function(fn,arg){await this._p._ensure();var r=await this._p._ctx.cmd({op:"evaluar",fn:String(fn),esFn:true,arg:ENC(arg),loc:this._s,todos:true});if(!r.ok)throw Fallo("El código de la prueba ha fallado dentro de la página: "+r.error,"locator.evaluateAll: "+r.error,SITE());return DEC(r.value)};
Locator.prototype.waitFor=async function(o){o=o||{};var state=o.state||"visible",site=SITE(),ctx=this._p._ctx;ctx.step("Esperar a que "+HUMAN(this._s)+({visible:" se vea",hidden:" desaparezca",attached:" esté en la página",detached:" ya no esté"})[state]);await this._p._ensure();var to=o.timeout>0?o.timeout:ctx.actionTimeout(),dl=now()+to;
for(var i=0;;i++){var r=await ctx.cmd({op:"estado",loc:this._s,campos:["vis"],max:2});if(!r.ok)throw Fallo(r.error,r.error,site);var v=r.value;if(v.n>1&&(state==="visible"||state==="hidden"))throw Fallo("No he podido esperar a "+HUMAN(this._s)+": hay "+v.n+" que coinciden y no sé cuál.","locator.waitFor: strict mode violation: resolved to "+v.n+" elements",site);
var okk=state==="attached"?v.n>0:state==="detached"?v.n===0:state==="visible"?v.n===1&&v.items[0].vis:v.n===0||!v.items[0].vis;if(okk)return;if(now()>=dl)break;await ctx.sleep(i<10?50:150)}
throw Fallo(HUMAN(this._s).replace(/^./,function(c){return c.toUpperCase()})+({visible:" no ha aparecido",hidden:" no ha desaparecido",attached:" no ha llegado a estar en la página",detached:" sigue en la página"})[state]+" en "+Math.round(to/1000)+" s.","locator.waitFor: Timeout "+to+"ms exceeded.\nLocator: "+TECH(this._s)+"\n  - waiting for "+state,site)};

// ------------------------------------------------------------------ expect
var EQ=function(a,b,strict){if(b&&b.__asym)return b.match(a);if(Object.is(a,b))return true;if(typeof a!==typeof b||a===null||b===null||typeof a!=="object")return false;if(a instanceof Date||b instanceof Date)return a instanceof Date&&b instanceof Date&&a.getTime()===b.getTime();if(a instanceof RegExp||b instanceof RegExp)return String(a)===String(b);
if(Array.isArray(a)!==Array.isArray(b))return false;if(Array.isArray(a)){if(a.length!==b.length)return false;for(var i=0;i<a.length;i++)if(!EQ(a[i],b[i],strict))return false;return true}
if(a instanceof Map||b instanceof Map){if(!(a instanceof Map&&b instanceof Map)||a.size!==b.size)return false;var ok=true;a.forEach(function(v,k){if(!b.has(k)||!EQ(v,b.get(k),strict))ok=false});return ok}
if(a instanceof Set||b instanceof Set){if(!(a instanceof Set&&b instanceof Set)||a.size!==b.size)return false;var ok2=true;a.forEach(function(v){if(!b.has(v))ok2=false});return ok2}
if(strict&&Object.getPrototypeOf(a)!==Object.getPrototypeOf(b))return false;var ka=Object.keys(a).filter(function(k){return strict||a[k]!==undefined}),kb=Object.keys(b).filter(function(k){return strict||b[k]!==undefined});if(ka.length!==kb.length)return false;for(var j=0;j<ka.length;j++){if(!Object.prototype.hasOwnProperty.call(b,ka[j]))return false;if(!EQ(a[ka[j]],b[ka[j]],strict))return false}return true};
var SUBSET=function(obj,sub){if(sub&&sub.__asym)return sub.match(obj);if(Array.isArray(sub)){if(!Array.isArray(obj)||obj.length!==sub.length)return false;for(var i=0;i<sub.length;i++)if(!SUBSET(obj[i],sub[i]))return false;return true}if(sub&&typeof sub==="object"&&!(sub instanceof Date)&&!(sub instanceof RegExp)){if(!obj||typeof obj!=="object")return false;for(var k in sub)if(!SUBSET(obj[k],sub[k]))return false;return true}return EQ(obj,sub,false)};
var ASYM=function(match,desc){return {__asym:true,match:match,toJSON:function(){return desc}}};
var PATHGET=function(o,path){var parts=Array.isArray(path)?path:String(path).replace(/\[(\d+)\]/g,".$1").split(".").filter(Boolean);var cur=o;for(var i=0;i<parts.length;i++){if(cur==null||!(parts[i] in Object(cur)))return {has:false};cur=cur[parts[i]]}return {has:true,v:cur}};
var MATCHTXT=function(got,exp,full,ic){got=NORM(got);if(exp instanceof RegExp){exp.lastIndex=0;return exp.test(got)}var e=NORM(exp);if(ic){got=got.toLowerCase();e=e.toLowerCase()}return full?got===e:got.indexOf(e)>=0};
function Expect(actual,o){this.a=actual;this.o=o||{};this.not=null}
var VALUE_MATCHERS={
toBe:function(a,e){return {pass:Object.is(a,e),plano:"Esperaba "+ES(e)+", pero salió "+ES(a)+".",det:"expect(received).toBe(expected)\n\nExpected: "+J(e)+"\nReceived: "+J(a)}},
toEqual:function(a,e){return {pass:EQ(a,e,false),plano:"Esperaba "+ES(e)+", pero salió "+ES(a)+".",det:"expect(received).toEqual(expected)\n\nExpected: "+J(e)+"\nReceived: "+J(a)}},
toStrictEqual:function(a,e){return {pass:EQ(a,e,true),plano:"Esperaba "+ES(e)+", pero salió "+ES(a)+".",det:"expect(received).toStrictEqual(expected)\n\nExpected: "+J(e)+"\nReceived: "+J(a)}},
toBeTruthy:function(a){return {pass:!!a,plano:"Esperaba algo que valiera (verdadero), pero salió "+ES(a)+".",det:"expect(received).toBeTruthy()\n\nReceived: "+J(a)}},
toBeFalsy:function(a){return {pass:!a,plano:"Esperaba algo vacío o falso, pero salió "+ES(a)+".",det:"expect(received).toBeFalsy()\n\nReceived: "+J(a)}},
toBeNull:function(a){return {pass:a===null,plano:"Esperaba null, pero salió "+ES(a)+".",det:"expect(received).toBeNull()\n\nReceived: "+J(a)}},
toBeUndefined:function(a){return {pass:a===undefined,plano:"Esperaba nada (undefined), pero salió "+ES(a)+".",det:"expect(received).toBeUndefined()\n\nReceived: "+J(a)}},
toBeDefined:function(a){return {pass:a!==undefined,plano:"Esperaba un valor, pero no hay ninguno (undefined).",det:"expect(received).toBeDefined()\n\nReceived: undefined"}},
toBeNaN:function(a){return {pass:typeof a==="number"&&isNaN(a),plano:"Esperaba NaN, pero salió "+ES(a)+".",det:"expect(received).toBeNaN()\n\nReceived: "+J(a)}},
toContain:function(a,e){var p=a!=null&&typeof a.indexOf==="function"?a.indexOf(e)>=0:a instanceof Set?a.has(e):false;return {pass:p,plano:"Esperaba que "+ES(a)+" contuviera "+ES(e)+".",det:"expect(received).toContain(expected)\n\nExpected: "+J(e)+"\nReceived: "+J(a)}},
toContainEqual:function(a,e){var p=Array.isArray(a)&&a.some(function(x){return EQ(x,e,false)});return {pass:p,plano:"Esperaba que "+ES(a)+" contuviera "+ES(e)+".",det:"expect(received).toContainEqual(expected)\n\nExpected: "+J(e)+"\nReceived: "+J(a)}},
toHaveLength:function(a,e){var l=a!=null?a.length:undefined;return {pass:l===e,plano:"Esperaba "+e+" elemento(s), pero hay "+ES(l)+".",det:"expect(received).toHaveLength(expected)\n\nExpected length: "+e+"\nReceived length: "+J(l)}},
toMatch:function(a,e){var p=typeof a==="string"&&(e instanceof RegExp?(e.lastIndex=0,e.test(a)):a.indexOf(String(e))>=0);return {pass:p,plano:"Esperaba que "+ES(a)+" encajara con "+ES(e)+".",det:"expect(received).toMatch(expected)\n\nExpected pattern: "+J(e)+"\nReceived string: "+J(a)}},
toMatchObject:function(a,e){return {pass:SUBSET(a,e),plano:"Esperaba que "+ES(a)+" tuviera "+ES(e)+".",det:"expect(received).toMatchObject(expected)\n\nExpected: "+J(e)+"\nReceived: "+J(a)}},
toBeGreaterThan:function(a,e){return {pass:a>e,plano:"Esperaba más de "+e+", pero salió "+ES(a)+".",det:"expect(received).toBeGreaterThan(expected)\n\nExpected: > "+e+"\nReceived: "+J(a)}},
toBeGreaterThanOrEqual:function(a,e){return {pass:a>=e,plano:"Esperaba "+e+" o más, pero salió "+ES(a)+".",det:"expect(received).toBeGreaterThanOrEqual(expected)\n\nExpected: >= "+e+"\nReceived: "+J(a)}},
toBeLessThan:function(a,e){return {pass:a<e,plano:"Esperaba menos de "+e+", pero salió "+ES(a)+".",det:"expect(received).toBeLessThan(expected)\n\nExpected: < "+e+"\nReceived: "+J(a)}},
toBeLessThanOrEqual:function(a,e){return {pass:a<=e,plano:"Esperaba "+e+" o menos, pero salió "+ES(a)+".",det:"expect(received).toBeLessThanOrEqual(expected)\n\nExpected: <= "+e+"\nReceived: "+J(a)}},
toBeCloseTo:function(a,e,d){d=d==null?2:d;var p=Math.abs(e-a)<Math.pow(10,-d)/2;return {pass:p,plano:"Esperaba casi "+e+", pero salió "+ES(a)+".",det:"expect(received).toBeCloseTo(expected, "+d+")\n\nExpected: "+e+"\nReceived: "+J(a)}},
toHaveProperty:function(a,path,v){var g=PATHGET(a,path),p=g.has&&(arguments.length<3||EQ(g.v,v,false));return {pass:p,plano:"Esperaba que tuviera "+Q(String(path))+(arguments.length>=3?" con "+ES(v):"")+(g.has?", pero vale "+ES(g.v):", pero no lo tiene")+".",det:"expect(received).toHaveProperty(path"+(arguments.length>=3?", value":"")+")\n\nExpected path: "+J(path)+(arguments.length>=3?"\nExpected value: "+J(v):"")+"\nReceived: "+J(g.has?g.v:a)}},
toBeInstanceOf:function(a,C){return {pass:a instanceof C,plano:"Esperaba un "+(C&&C.name||"objeto")+", pero salió "+ES(a)+".",det:"expect(received).toBeInstanceOf(expected)\n\nExpected constructor: "+(C&&C.name)+"\nReceived: "+J(a)}},
toThrow:function(a,e){var thrown=null,did=false;if(typeof a==="function"){try{a()}catch(x){did=true;thrown=x}}var msg=thrown&&thrown.message!=null?String(thrown.message):String(thrown);var p=did&&(e==null||(e instanceof RegExp?e.test(msg):typeof e==="string"?msg.indexOf(e)>=0:typeof e==="function"?thrown instanceof e:e&&e.message!=null?msg===e.message:true));return {pass:p,plano:did?"Esperaba otro error, pero salió "+Q(msg)+".":"Esperaba un error, pero no ha habido ninguno.",det:"expect(received).toThrow(expected)\n\nExpected: "+J(e)+"\nReceived: "+(did?J(msg):"did not throw")}}};
VALUE_MATCHERS.toThrowError=VALUE_MATCHERS.toThrow;
// Las comprobaciones de lo que se ve (esperan, como Playwright).
var SINGLE=function(v,what,loc){if(v.n>1)return {error:true,plano:"No he podido comprobar "+HUMAN(loc._s)+": hay "+v.n+" que coinciden y no sé cuál (hay que concretar más la prueba).",det:"expect(locator)."+what+"() failed\n\nLocator: "+TECH(loc._s)+"\nError: strict mode violation: resolved to "+v.n+" elements"};return null};
var LOC_MATCHERS={
toBeVisible:{campos:["vis"],eval:function(v,o){if(o&&o.visible===false)return LOC_MATCHERS.toBeHidden.eval(v,o);return v.n===1?{pass:!!v.items[0].vis,got:v.items[0].vis?"se ve":"está en la página pero no se ve"}:{pass:false,got:"no está en la página"}},plano:function(h,got,neg){return neg?"Esperaba que "+h+" NO se viera, pero se ve.":"Esperaba ver "+h+", pero "+got+"."},exp:function(){return "visible"}},
toBeHidden:{campos:["vis"],eval:function(v){return v.n===1?{pass:!v.items[0].vis,got:v.items[0].vis?"se ve":"no se ve"}:{pass:true,got:"no está"}},plano:function(h,got,neg){return neg?"Esperaba ver "+h+", pero "+(got==="no está"?"no está en la página":"no se ve")+".":"Esperaba que "+h+" no se viera, pero se ve."},exp:function(){return "hidden"}},
toBeAttached:{campos:[],eval:function(v,o){var want=!(o&&o.attached===false);return {pass:want?v.n===1:v.n===0,got:v.n?"está":"no está"}},plano:function(h,got,neg){return neg?"Esperaba que "+h+" no estuviera en la página, pero está.":"Esperaba que "+h+" estuviera en la página, pero no está."},exp:function(){return "attached"}},
toHaveCount:{multi:true,campos:[],eval:function(v,o,e){return {pass:v.n===e,got:String(v.n)}},plano:function(h,got,neg,e){return neg?"Esperaba que no hubiera "+e+" ("+h+"), pero hay "+got+".":"Esperaba "+e+" ("+h+"), pero hay "+got+"."},exp:function(e){return String(e)}},
toHaveText:{multi:true,campos:["txt","inner"],eval:function(v,o,e){var key=o&&o.useInnerText?"inner":"txt",ic=o&&o.ignoreCase;if(Array.isArray(e)){var got=v.items.map(function(x){return NORM(x[key])});var p=v.n===e.length&&e.every(function(x,i){return MATCHTXT(v.items[i]&&v.items[i][key],x,true,ic)});return {pass:p,got:got}}if(v.n>1)return {strict:true};return v.n===1?{pass:MATCHTXT(v.items[0][key],e,true,ic),got:NORM(v.items[0][key])}:{pass:false,got:null}},
plano:function(h,got,neg,e){if(Array.isArray(e))return neg?"Esperaba que "+h+" no dijeran "+e.map(ES).join(", ")+", pero lo dicen.":"Esperaba "+e.length+" ("+h+") que dijeran "+e.map(ES).join(", ")+"; hay "+(got?got.length:0)+(got&&got.length?": "+got.map(function(x){return Q(x)}).join(", "):"")+".";return neg?"Esperaba que "+h+" no dijera "+ES(e)+", pero lo dice.":got===null?"Esperaba que "+h+" dijera "+ES(e)+", pero no está en la página.":"Esperaba que "+h+" dijera "+ES(e)+", pero dice "+Q(got)+"."},exp:function(e){return J(e)}},
toContainText:{multi:true,campos:["txt","inner"],eval:function(v,o,e){var key=o&&o.useInnerText?"inner":"txt",ic=o&&o.ignoreCase;if(Array.isArray(e)){var j=0;for(var i=0;i<v.items.length&&j<e.length;i++)if(MATCHTXT(v.items[i][key],e[j],false,ic))j++;return {pass:j===e.length,got:v.items.map(function(x){return NORM(x[key])})}}if(v.n>1)return {strict:true};return v.n===1?{pass:MATCHTXT(v.items[0][key],e,false,ic),got:NORM(v.items[0][key])}:{pass:false,got:null}},
plano:function(h,got,neg,e){if(Array.isArray(e))return neg?"Esperaba que "+h+" no contuvieran "+e.map(ES).join(", ")+".":"Esperaba que "+h+" contuvieran "+e.map(ES).join(", ")+"; dicen "+(got&&got.length?got.map(function(x){return Q(x)}).join(", "):"nada")+".";return neg?"Esperaba que "+h+" no contuviera "+ES(e)+", pero lo contiene.":got===null?"Esperaba que "+h+" contuviera "+ES(e)+", pero no está en la página.":"Esperaba que "+h+" contuviera "+ES(e)+", pero dice "+Q(got)+"."},exp:function(e){return J(e)}},
toHaveValue:{campos:["val"],eval:function(v,o,e){if(v.n!==1)return {pass:false,got:null};var g=v.items[0].val==null?"":v.items[0].val;return {pass:e instanceof RegExp?(e.lastIndex=0,e.test(g)):g===String(e),got:g}},plano:function(h,got,neg,e){return neg?"Esperaba que "+h+" no tuviera "+ES(e)+", pero lo tiene.":got===null?"Esperaba que "+h+" tuviera "+ES(e)+", pero no está en la página.":"Esperaba que "+h+" tuviera "+ES(e)+", pero tiene "+Q(got)+"."},exp:function(e){return J(e)}},
toHaveValues:{campos:["val"],eval:function(v,o,e){if(v.n!==1)return {pass:false,got:null};var g=v.items[0].vals||[];return {pass:g.length===e.length&&e.every(function(x,i){return x instanceof RegExp?x.test(g[i]):g[i]===String(x)}),got:g}},plano:function(h,got,neg,e){return "Esperaba que en "+h+" estuvieran elegidas "+e.map(ES).join(", ")+(got?", pero están "+got.map(function(x){return Q(x)}).join(", "):"")+"."},exp:function(e){return J(e)}},
toBeChecked:{campos:["chk"],eval:function(v,o){var want=o&&o.checked===false?false:true;if(o&&o.indeterminate)return v.n===1?{pass:v.items[0].chk==="mixed",got:String(v.items[0].chk)}:{pass:false,got:null};return v.n===1?{pass:v.items[0].chk===want,got:v.items[0].chk===true?"marcada":"sin marcar"}:{pass:false,got:null}},plano:function(h,got,neg,e,o){var want=o&&o.checked===false?"sin marcar":"marcada";if(neg)want=want==="marcada"?"sin marcar":"marcada";return got===null?"Esperaba "+h+" "+want+", pero no está en la página.":"Esperaba "+h+" "+want+", pero está "+got+"."},exp:function(){return "checked"}},
toBeEnabled:{campos:["en"],eval:function(v,o){var want=!(o&&o.enabled===false);return v.n===1?{pass:v.items[0].en===want,got:v.items[0].en?"activo":"desactivado"}:{pass:false,got:null}},plano:function(h,got,neg,e,o){var want=(o&&o.enabled===false)!==neg?"desactivado":"activo";return got===null?"Esperaba "+h+" "+want+", pero no está en la página.":"Esperaba "+h+" "+want+", pero está "+got+"."},exp:function(){return "enabled"}},
toBeDisabled:{campos:["en"],eval:function(v){return v.n===1?{pass:!v.items[0].en,got:v.items[0].en?"activo":"desactivado"}:{pass:false,got:null}},plano:function(h,got,neg){var want=neg?"activo":"desactivado";return got===null?"Esperaba "+h+" "+want+", pero no está en la página.":"Esperaba "+h+" "+want+", pero está "+got+"."},exp:function(){return "disabled"}},
toBeEditable:{campos:["ed"],eval:function(v,o){var want=!(o&&o.editable===false);return v.n===1?{pass:v.items[0].ed===want,got:v.items[0].ed?"se puede escribir":"no se puede escribir"}:{pass:false,got:null}},plano:function(h,got,neg){return got===null?"Esperaba poder escribir en "+h+", pero no está en la página.":"Esperaba "+(neg?"no poder":"poder")+" escribir en "+h+", pero "+got+"."},exp:function(){return "editable"}},
toBeFocused:{campos:["foc"],eval:function(v){return v.n===1?{pass:!!v.items[0].foc,got:v.items[0].foc?"tiene el foco":"no tiene el foco"}:{pass:false,got:null}},plano:function(h,got,neg){return neg?"Esperaba que "+h+" no tuviera el foco, pero lo tiene.":got===null?"Esperaba que "+h+" tuviera el foco, pero no está en la página.":"Esperaba que "+h+" tuviera el foco, pero no lo tiene."},exp:function(){return "focused"}},
toBeEmpty:{campos:["empty","txt","val"],eval:function(v){return v.n===1?{pass:!!v.items[0].empty,got:v.items[0].val!=null?v.items[0].val:NORM(v.items[0].txt)}:{pass:false,got:null}},plano:function(h,got,neg){return neg?"Esperaba que "+h+" tuviera algo, pero está vacío.":got===null?"Esperaba "+h+" vacío, pero no está en la página.":"Esperaba "+h+" vacío, pero tiene "+Q(got)+"."},exp:function(){return "empty"}},
toBeInViewport:{campos:["inview"],eval:function(v){return v.n===1?{pass:!!v.items[0].inview,got:v.items[0].inview?"se ve en pantalla":"no está en la pantalla"}:{pass:false,got:null}},plano:function(h,got,neg){return neg?"Esperaba que "+h+" no estuviera en la pantalla, pero lo está.":"Esperaba "+h+" en la pantalla, pero "+(got||"no está en la página")+"."},exp:function(){return "in viewport"}},
toHaveAttribute:{campos:[],attrs:function(e){return [String(e)]},eval:function(v,o,e,val,hasVal){if(v.n!==1)return {pass:false,got:null};var g=v.items[0].attrs[String(e)];if(!hasVal)return {pass:g!==null&&g!==undefined,got:g};return {pass:g!=null&&(val instanceof RegExp?(val.lastIndex=0,val.test(g)):(o&&o.ignoreCase?String(g).toLowerCase()===String(val).toLowerCase():g===String(val))),got:g}},plano:function(h,got,neg,e,o,val,hasVal){return neg?"Esperaba que "+h+" no tuviera "+Q(e)+(hasVal?" = "+ES(val):"")+", pero lo tiene.":got==null?"Esperaba que "+h+" tuviera "+Q(e)+(hasVal?" = "+ES(val):"")+", pero no lo tiene.":"Esperaba que "+h+" tuviera "+Q(e)+" = "+ES(val)+", pero tiene "+Q(got)+"."},exp:function(e){return J(e)}},
toHaveClass:{multi:true,campos:["cls"],eval:function(v,o,e){var one=function(g,x){return x instanceof RegExp?(x.lastIndex=0,x.test(g)):NORM(g)===NORM(x)};if(Array.isArray(e))return {pass:v.n===e.length&&e.every(function(x,i){return one(v.items[i].cls,x)}),got:v.items.map(function(x){return x.cls})};if(v.n>1)return {strict:true};return v.n===1?{pass:one(v.items[0].cls,e),got:v.items[0].cls}:{pass:false,got:null}},plano:function(h,got,neg,e){return neg?"Esperaba que "+h+" no tuviera la clase "+ES(e)+".":"Esperaba que "+h+" tuviera la clase "+ES(e)+(got!=null?", pero tiene "+Q(Array.isArray(got)?got.join(" | "):got):", pero no está en la página")+"."},exp:function(e){return J(e)}},
toContainClass:{campos:["cls"],eval:function(v,o,e){if(v.n!==1)return {pass:false,got:null};var have=NORM(v.items[0].cls).split(" ");return {pass:String(e).split(/\s+/).filter(Boolean).every(function(c){return have.indexOf(c)>=0}),got:v.items[0].cls}},plano:function(h,got,neg,e){return neg?"Esperaba que "+h+" no tuviera la clase "+ES(e)+".":"Esperaba que "+h+" tuviera la clase "+ES(e)+(got!=null?", pero tiene "+Q(got):"")+"."},exp:function(e){return J(e)}},
toHaveId:{campos:["id"],eval:function(v,o,e){return v.n===1?{pass:e instanceof RegExp?e.test(v.items[0].id):v.items[0].id===String(e),got:v.items[0].id}:{pass:false,got:null}},plano:function(h,got,neg,e){return "Esperaba que "+h+(neg?" no":"")+" tuviera el id "+ES(e)+(got!=null?", pero tiene "+Q(got):"")+"."},exp:function(e){return J(e)}},
toHaveCSS:{campos:[],css:function(e){return [String(e)]},eval:function(v,o,e,val){if(v.n!==1)return {pass:false,got:null};var g=v.items[0].css[String(e)];return {pass:val instanceof RegExp?val.test(g):g===String(val),got:g}},plano:function(h,got,neg,e,o,val){return "Esperaba que "+h+(neg?" no":"")+" tuviera "+e+": "+ES(val)+(got!=null?", pero tiene "+Q(got):"")+"."},exp:function(e){return J(e)}},
toHaveAccessibleName:{campos:["name"],eval:function(v,o,e){return v.n===1?{pass:e instanceof RegExp?e.test(v.items[0].name):MATCHTXT(v.items[0].name,e,true,o&&o.ignoreCase),got:v.items[0].name}:{pass:false,got:null}},plano:function(h,got,neg,e){return "Esperaba que "+h+(neg?" no":"")+" se llamara "+ES(e)+(got!=null?", pero se llama "+Q(got):"")+"."},exp:function(e){return J(e)}},
toHaveRole:{campos:["role"],eval:function(v,o,e){return v.n===1?{pass:v.items[0].role===String(e),got:v.items[0].role}:{pass:false,got:null}},plano:function(h,got,neg,e){return "Esperaba que "+h+(neg?" no":"")+" fuera "+Q(e)+(got!=null?", pero es "+Q(got):"")+"."},exp:function(e){return J(e)}},
toHaveJSProperty:{campos:[],props:function(e){return [String(e)]},eval:function(v,o,e,val){if(v.n!==1)return {pass:false,got:null};var g=v.items[0].props[String(e)];return {pass:EQ(g,val,false),got:g}},plano:function(h,got,neg,e,o,val){return "Esperaba que "+h+(neg?" no":"")+" tuviera "+e+" = "+ES(val)+", pero tiene "+ES(got)+"."},exp:function(e){return J(e)}}};
var LOCARGS=function(name,args){var e=args[0],o=null,val,hasVal=false;if(name==="toHaveAttribute"||name==="toHaveCSS"||name==="toHaveJSProperty"){hasVal=args.length>=2&&!(name==="toHaveAttribute"&&args[1]&&typeof args[1]==="object"&&!(args[1] instanceof RegExp));val=hasVal?args[1]:undefined;o=hasVal?args[2]:args[1]}else if(name==="toHaveCount"||name==="toHaveText"||name==="toContainText"||name==="toHaveValue"||name==="toHaveValues"||name==="toHaveClass"||name==="toContainClass"||name==="toHaveId"||name==="toHaveAccessibleName"||name==="toHaveRole"){o=args[1]}else{o=args[0];e=undefined}return {e:e,o:o||{},val:val,hasVal:hasVal}};
var LOCASSERT=async function(ex,name,args,neg,site){var m=LOC_MATCHERS[name],loc=ex.a,ctx=loc._p._ctx;var pa=LOCARGS(name,args);var e=pa.e,o=pa.o;ctx.step("Comprobar "+name+" en "+HUMAN(loc._s)+(e!==undefined?" ("+SL(J(e),60)+")":""));await loc._p._ensure();
var to=o.timeout!=null&&o.timeout>=0?o.timeout:ex.o.timeout!=null?ex.o.timeout:ctx.expectTimeout();var dl=now()+to,last=null;
var cmd={op:"estado",loc:loc._s,campos:m.campos,max:m.multi?500:2};if(m.attrs)cmd.attrs=m.attrs(e);if(m.css)cmd.css=m.css(e);if(m.props)cmd.props=m.props(e);
for(var i=0;;i++){var r=await ctx.cmd(cmd);if(!r.ok&&r.motivo==="navegando"){if(now()>=dl)break;await ctx.sleep(50);continue}if(!r.ok)throw Fallo("No he podido comprobar "+HUMAN(loc._s)+": "+r.error,"expect(locator)."+name+": "+r.error,site);var v=r.value;
var res=m.eval(v,o,e,pa.val,pa.hasVal);if(res.strict||(!m.multi&&v.n>1&&name!=="toBeAttached")){var s=SINGLE(v,name,loc);throw Fallo(s.plano,s.det,site)}
if(!!res.pass!==neg)return;last=res;if(now()>=dl)break;await ctx.sleep(i<10?50:100)}
var plano=(ex.o.message?ex.o.message+": ":"")+m.plano(HUMAN(loc._s),last&&last.got,neg,e,o,pa.val,pa.hasVal);
var det="expect(locator)."+(neg?"not.":"")+name+"("+(e!==undefined?"expected":"")+") failed\n\nLocator: "+TECH(loc._s)+"\nExpected: "+(neg?"not ":"")+m.exp(e)+"\nReceived: "+(last&&last.got===null?"<element(s) not found>":J(last&&last.got))+"\nTimeout: "+to+"ms";
throw Fallo(plano,det,site,{esperado:e!==undefined?J(e):m.exp(e),recibido:last&&last.got===null?null:J(last&&last.got)})};
var PAGE_MATCHERS={toHaveURL:function(v,e){return {pass:URLOK(e,v.url),got:v.url}},toHaveTitle:function(v,e){return {pass:e instanceof RegExp?(e.lastIndex=0,e.test(v.title)):NORM(v.title)===NORM(e),got:v.title}}};
var PAGEASSERT=async function(ex,name,args,neg,site){var page=ex.a,ctx=page._ctx,e=args[0],o=args[1]||{};ctx.step("Comprobar "+name+" ("+SL(J(e),60)+")");await page._ensure();var to=o.timeout!=null&&o.timeout>=0?o.timeout:ex.o.timeout!=null?ex.o.timeout:ctx.expectTimeout(),dl=now()+to,last=null;
for(var i=0;;i++){var v=await page._info();page._lastUrl=v.url;var res=PAGE_MATCHERS[name](v,e);if(!!res.pass!==neg)return;last=res;if(now()>=dl)break;await ctx.sleep(i<10?50:100)}
var plano=(ex.o.message?ex.o.message+": ":"")+(name==="toHaveURL"?(neg?"Esperaba no estar en "+ES(e)+", pero estoy ahí.":"Esperaba estar en "+ES(e)+", pero estoy en "+Q(last.got)+"."):(neg?"Esperaba que la página no se titulara "+ES(e)+".":"Esperaba que la página se titulara "+ES(e)+", pero se titula "+Q(last.got)+"."));
throw Fallo(plano,"expect(page)."+(neg?"not.":"")+name+"(expected) failed\n\nExpected: "+J(e)+"\nReceived: "+J(last.got)+"\nTimeout: "+to+"ms",site,{esperado:J(e),recibido:J(last.got)})};
var MAKE=function(actual,o,neg){var api={};var isLoc=actual instanceof Locator,isPage=actual instanceof Page;
var wrap=function(fn){return function(){var site=SITE();var args=Array.prototype.slice.call(arguments);var run=function(){return fn(args,site)};var soft=function(err){if(o.soft&&err&&err.name==="Fallo"&&!err.willy.parado&&!err.willy.tiempo&&CUR){CUR.soft.push(err);return undefined}throw err};
try{var r=run();if(r&&typeof r.then==="function")return r.then(function(x){return x},soft);return r}catch(err){return soft(err)}}};
if(isLoc)Object.keys(LOC_MATCHERS).forEach(function(n){api[n]=wrap(function(args,site){return LOCASSERT({a:actual,o:o},n,args,neg,site)})});
if(isPage)Object.keys(PAGE_MATCHERS).forEach(function(n){api[n]=wrap(function(args,site){return PAGEASSERT({a:actual,o:o},n,args,neg,site)})});
Object.keys(VALUE_MATCHERS).forEach(function(n){if(api[n])return;api[n]=wrap(function(args,site){if(CUR)CUR.step("Comprobar "+n);var res=VALUE_MATCHERS[n].apply(null,[actual].concat(args));if(!!res.pass!==neg)return;throw Fallo((o.message?o.message+": ":"")+(neg?"No esperaba eso: "+res.plano:res.plano),(neg?res.det.replace("expect(received).","expect(received).not."):res.det),site,{esperado:J(args[0]),recibido:J(actual)})})});
["toHaveScreenshot","toMatchSnapshot","toMatchAriaSnapshot"].forEach(function(n){api[n]=wrap(function(args,site){throw Fallo("La prueba compara capturas ("+n+"): WILLY no guarda capturas de referencia. Comprueba lo que se ve con toBeVisible, toHaveText…",n+" is not supported by the WILLY test runner.",site,{nosoportado:true})})});
api.resolves=null;api.rejects=null;return api};
var expect=function(actual,m){var o=typeof m==="string"?{message:m}:(m||{});var api=MAKE(actual,o,false);api.not=MAKE(actual,o,true);return api};
expect.soft=function(actual,m){var o=typeof m==="string"?{message:m}:(m||{});o.soft=true;var api=MAKE(actual,o,false);api.not=MAKE(actual,o,true);return api};
expect.configure=function(c){var f=function(a,m){var o=typeof m==="string"?{message:m}:(m||{});if(c.timeout!=null)o.timeout=c.timeout;if(c.soft)o.soft=true;var api=MAKE(a,o,false);api.not=MAKE(a,o,true);return api};f.soft=expect.soft;f.poll=expect.poll;f.configure=expect.configure;return f};
expect.poll=function(fn,o){o=o||{};var mk=function(neg){var api={};Object.keys(VALUE_MATCHERS).forEach(function(n){api[n]=async function(){var site=SITE(),args=Array.prototype.slice.call(arguments),ctx=CUR;var to=o.timeout!=null?o.timeout:ctx?ctx.expectTimeout():5000,dl=now()+to,last=null,iv=o.intervals||[100,250,500,1000];
for(var i=0;;i++){var val=await fn();var res=VALUE_MATCHERS[n].apply(null,[val].concat(args));if(!!res.pass!==neg)return;last=res;if(now()>=dl)break;await (ctx?ctx.sleep(iv[Math.min(i,iv.length-1)]):new Promise(function(r){setTimeout(r,100)}))}throw Fallo((o.message?o.message+": ":"")+last.plano+" (esperando "+Math.round(to/1000)+" s)","expect.poll: "+last.det,site)}});return api};var api=mk(false);api.not=mk(true);return api};
expect.any=function(C){return ASYM(function(v){return v!=null&&(v.constructor===C||v instanceof C||(C===Number&&typeof v==="number")||(C===String&&typeof v==="string")||(C===Boolean&&typeof v==="boolean"))},"Any<"+(C&&C.name)+">")};
expect.anything=function(){return ASYM(function(v){return v!=null},"Anything")};
expect.objectContaining=function(o){return ASYM(function(v){return SUBSET(v,o)},"ObjectContaining")};expect.arrayContaining=function(a){return ASYM(function(v){return Array.isArray(v)&&a.every(function(x){return v.some(function(y){return EQ(y,x,false)})})},"ArrayContaining")};
expect.stringContaining=function(s){return ASYM(function(v){return typeof v==="string"&&v.indexOf(s)>=0},"StringContaining")};expect.stringMatching=function(r){return ASYM(function(v){return typeof v==="string"&&(r instanceof RegExp?r.test(v):new RegExp(r).test(v))},"StringMatching")};
expect.extend=NOSOP("expect.extend()");

// ------------------------------------------------------------------ test, describe y compañía
var DEVICES={"Desktop Chrome":{viewport:{width:1280,height:720}},"Desktop Edge":{viewport:{width:1280,height:720}},"Desktop Firefox":{viewport:{width:1280,height:720}},"Desktop Safari":{viewport:{width:1280,height:720}},
"iPhone 12":{viewport:{width:390,height:664},isMobile:true,hasTouch:true},"iPhone 13":{viewport:{width:390,height:664},isMobile:true,hasTouch:true},"iPhone 14":{viewport:{width:390,height:664},isMobile:true,hasTouch:true},"iPhone 15":{viewport:{width:393,height:659},isMobile:true,hasTouch:true},"iPhone SE":{viewport:{width:320,height:568},isMobile:true,hasTouch:true},
"Pixel 5":{viewport:{width:393,height:727},isMobile:true,hasTouch:true},"Pixel 7":{viewport:{width:412,height:839},isMobile:true,hasTouch:true},"Galaxy S9+":{viewport:{width:320,height:658},isMobile:true,hasTouch:true},"iPad (gen 7)":{viewport:{width:810,height:1080},isMobile:true,hasTouch:true},"iPad Mini":{viewport:{width:768,height:1024},isMobile:true,hasTouch:true},"iPad Pro 11":{viewport:{width:834,height:1194},isMobile:true,hasTouch:true}};
var DEVPROXY=typeof Proxy==="function"?new Proxy(DEVICES,{get:function(t,k){if(typeof k!=="string")return undefined;if(t[k])return t[k];var low=k.toLowerCase();if(/landscape/.test(low)){var base=t[k.replace(/\s*landscape\s*/i,"").trim()];if(base)return {viewport:{width:base.viewport.height,height:base.viewport.width},isMobile:base.isMobile,hasTouch:base.hasTouch}}if(/iphone|pixel|galaxy|android|mobile|móvil/.test(low))return {viewport:{width:390,height:664},isMobile:true,hasTouch:true};if(/ipad|tablet|tab /.test(low))return {viewport:{width:810,height:1080},isMobile:true,hasTouch:true};return {viewport:{width:1280,height:720}}}}):DEVICES;
var FILEIDX=0,SUITE=null,ALL=[],IDS={};
function Suite(title,parent,file){this.title=title;this.parent=parent;this.file=file;this.items=[];this.hooks={beforeAll:[],afterAll:[],beforeEach:[],afterEach:[]};this.use={};this.only=false;this.skip=false;this.timeout=null;this.ranBeforeAll=false;this.left=0;this.fixtures=parent?parent.fixtures:[]}
var chainOf=function(s){var out=[];for(var c=s;c;c=c.parent)out.unshift(c);return out};
var titlePath=function(t){return chainOf(t.suite).filter(function(s){return s.parent}).map(function(s){return s.title}).concat([t.title])};
var MKTEST=function(fixtures){
var api=function(title,a,b){return add(title,typeof a==="function"?a:b,{})};
var add=function(title,fn,flags){if(!SUITE)throw Fallo("test() solo se puede usar al cargar el archivo de pruebas.","test() called outside of a test file",SITE());if(typeof fn!=="function")throw Fallo("La prueba "+Q(title)+" no tiene función.","test("+J(title)+"): missing test function",SITE());
var s=SUITE,path=chainOf(s).filter(function(x){return x.parent}).map(function(x){return x.title}).concat([String(title)]);var id=s.file+" \u203a "+path.join(" \u203a ");var k=id,n=2;while(IDS[k])k=id+" ("+(n++)+")";IDS[k]=1;
var t={id:k,title:String(title),fn:fn,suite:s,file:s.file,only:!!flags.only,skip:!!flags.skip,skipWhy:flags.why||"",fail:!!flags.fail,slow:false,site:SITE(),fixtures:fixtures,timeoutMs:null};s.items.push(t);ALL.push(t);return t};
api.only=function(title,a,b){return add(title,typeof a==="function"?a:b,{only:true})};
var skipLike=function(kind){return function(a,b,c){if(typeof a==="string"&&(typeof b==="function"||typeof c==="function"))return add(a,typeof b==="function"?b:c,kind==="fail"?{fail:true}:{skip:true,why:kind});var cond=arguments.length===0?true:typeof a==="function"?null:a,why=typeof b==="string"?b:typeof a==="string"?a:"";if(CUR){if(cond===null)cond=a({browserName:"chromium",isMobile:false});if(cond){if(kind==="fail"){CUR.expectFail=true;return}throw Fallo("(saltada)","skipped",null,{saltada:true,why:why||kind})}return}
if(SUITE){if(cond===null){SUITE.skipIf=SUITE.skipIf||[];SUITE.skipIf.push({fn:a,why:why,kind:kind});return}if(cond){if(kind==="fail")SUITE.failAll=true;else{SUITE.skip=true;SUITE.skipWhy=why||kind}}}}};
api.skip=skipLike("skip");api.fixme=skipLike("fixme");api.fail=skipLike("fail");api.slow=function(){if(CUR){CUR.deadline+=CUR.timeout*2;CUR.timeout*=3}else if(SUITE)SUITE.slow=true};
var describe=function(title,fn,flags){if(typeof title==="function"){fn=title;title=""}var s=new Suite(String(title),SUITE,SUITE.file);s.only=!!(flags&&flags.only);s.skip=!!(flags&&flags.skip);SUITE.items.push(s);var prev=SUITE;SUITE=s;try{fn()}finally{SUITE=prev}return s};
api.describe=function(t,f){return describe(t,f)};api.describe.only=function(t,f){return describe(t,f,{only:true})};api.describe.skip=function(t,f){return describe(t,f,{skip:true})};api.describe.fixme=api.describe.skip;api.describe.serial=function(t,f){return describe(t,f)};api.describe.serial.only=api.describe.only;api.describe.serial.skip=api.describe.skip;api.describe.parallel=api.describe.serial;api.describe.parallel.only=api.describe.only;
api.describe.configure=function(o){if(SUITE&&o&&o.timeout)SUITE.timeout=Number(o.timeout)};
["beforeEach","afterEach","beforeAll","afterAll"].forEach(function(h){api[h]=function(a,b){var fn=typeof a==="function"?a:b;if(SUITE)SUITE.hooks[h].push(fn)}});
api.use=function(o){if(SUITE&&o){for(var k in o)SUITE.use[k]=o[k]}};
api.setTimeout=function(ms){ms=Number(ms)||0;if(ms<=0)ms=120000;if(CUR){CUR.deadline=CUR.started+ms;CUR.timeout=ms}else if(SUITE)SUITE.timeout=ms};
api.step=async function(title,fn){if(CUR)CUR.step("Paso: "+title);return fn()};api.step.skip=async function(){};
api.info=function(){var c=CUR;return {title:c?c.t.title:"",titlePath:c?titlePath(c.t):[],file:c?c.t.file:"",line:0,column:0,timeout:c?c.timeout:0,annotations:[],attachments:[],retry:0,repeatEachIndex:0,workerIndex:0,parallelIndex:0,project:{name:"chromium",use:{}},config:{},outputDir:"",snapshotDir:"",status:"passed",skip:api.skip,fixme:api.fixme,fail:api.fail,slow:api.slow,setTimeout:api.setTimeout,attach:async function(){},outputPath:function(){return ""},snapshotPath:function(){return ""}}};
api.extend=function(defs){return MKTEST(fixtures.concat([defs||{}]))};
api.expect=expect;api.request=null;return api};
var TEST=MKTEST([]);
var PW={test:TEST,expect:expect,devices:DEVPROXY,chromium:{launch:NOSOP("chromium.launch()")},firefox:null,webkit:null,defineConfig:function(c){return c},request:null,selectors:{setTestIdAttribute:function(){}}};

// ------------------------------------------------------------------ cargar los archivos y pasar las pruebas
var LOADERRS=[];
var loadFiles=async function(){window.__willyArchivo={};for(var i=0;i<FILES.length;i++){var f=FILES[i];var url="willy-prueba-"+i+"/"+f.path;URLS.push({url:url,path:f.path,map:f.lineMap||null});var root=new Suite("",null,f.path);var synErr=null;
var onErr=function(ev){if(!synErr)synErr={mensaje:String(ev.message||"Error").replace(/^Uncaught /,""),linea:ev.lineno||0};ev.preventDefault()};addEventListener("error",onErr);
var s=document.createElement("script");s.textContent="window.__willyArchivo["+i+"]=async function(__pw){"+f.code+"\n};\n//# sourceURL="+url;document.head.appendChild(s);removeEventListener("error",onErr);
if(synErr||typeof window.__willyArchivo[i]!=="function"){var e0=synErr||{mensaje:"El archivo no se puede leer",linea:0};var ln=e0.linea;if(f.lineMap&&f.lineMap[ln-1])ln=f.lineMap[ln-1];LOADERRS.push({archivo:f.path,mensaje:e0.mensaje,linea:ln});continue}
SUITE=root;try{await window.__willyArchivo[i](PW)}catch(err){var w=WHERE(err&&err.stack);LOADERRS.push({archivo:f.path,mensaje:err&&err.willy?err.willy.plano:(err&&err.name?err.name+": ":"")+(err&&err.message||String(err)),linea:w?w.linea:0})}SUITE=null;ROOTS.push(root)}};
var ROOTS=[];
var eff=function(t){var chain=chainOf(t.suite);var use={},timeout=null,skip=false,why="",only=t.only,failAll=false;chain.forEach(function(s){for(var k in s.use)use[k]=s.use[k];if(s.timeout)timeout=s.timeout;if(s.skip){skip=true;why=s.skipWhy||"skip"}if(s.only)only=true;if(s.failAll)failAll=true;(s.skipIf||[]).forEach(function(c){try{if(c.fn({browserName:"chromium",isMobile:!!use.isMobile,viewport:use.viewport})){skip=true;why=c.why||c.kind}}catch(e){}})});
if(t.skip){skip=true;why=t.skipWhy||"skip"}return {use:use,timeout:timeout,skip:skip,why:why,only:only,fail:t.fail||failAll,slow:chain.some(function(s){return s.slow})}};
var RESULT=function(t,ctx,estado,err,ms){var r={id:t.id,archivo:t.file,titulo:titlePath(t).join(" \u203a "),estado:estado,ms:ms,pasos:ctx?ctx.steps.slice(-12):[],erroresPagina:ctx?ctx.pageErrors.slice(0,5):[],dialogos:ctx?ctx.dialogs.slice(0,5):[]};
var reg=WHERE(t.site);if(reg)r.linea=reg.linea;if(err){var w=err.willy||{plano:(err.name?err.name+": ":"")+(err.message||String(err)),detalle:String(err.stack||err.message||err).split("\n").slice(0,6).join("\n"),site:err.stack};var where=WHERE(w.site)||WHERE(err.stack)||reg;
r.error={plano:w.plano,detalle:w.detalle,linea:where?where.linea:0,archivo:where?where.archivo:t.file,tiempo:!!w.tiempo,nosoportado:!!w.nosoportado,esperado:w.esperado!=null?w.esperado:null,recibido:w.recibido!=null?w.recibido:null,enPrueba:!err.willy}}return r};
var withTimeout=function(ctx,fn){return new Promise(function(resolve,reject){var done=false;var iv=setInterval(function(){if(done)return;if(ctx.aborted==="parado"){done=true;clearInterval(iv);reject(Fallo("Pruebas paradas.","Stopped.",null,{parado:true}));return}if(now()>ctx.deadline){done=true;clearInterval(iv);ctx.gen++;reject(Fallo("La prueba ha tardado más de "+Math.round(ctx.timeout/1000)+" s y se ha parado"+(ctx.steps.length?" (iba por: "+SL(ctx.steps[ctx.steps.length-1],100)+")":"")+".","Test timeout of "+ctx.timeout+"ms exceeded.",null,{tiempo:true}))}},50);
Promise.resolve().then(fn).then(function(v){if(!done){done=true;clearInterval(iv);resolve(v)}},function(e){if(!done){done=true;clearInterval(iv);reject(e)}})})};
var setupFixtures=async function(defs,base,info){var teardowns=[];for(var i=0;i<defs.length;i++){var layer=defs[i];for(var name in layer){var def=layer[name];var opts=null;if(Array.isArray(def)){opts=def[1]||{};def=def[0]}
if(typeof def!=="function"){base[name]=def;continue}(function(nm,fn){var release,finished;var ready=new Promise(function(res,rej){var p;try{p=Promise.resolve(fn(base,function(v){base[nm]=v;res();return new Promise(function(r){release=r})},info))}catch(e){rej(e);return}finished=p.then(function(){res()},function(e){rej(e)})});teardowns.push({ready:ready,release:function(){if(release)release();return finished}})})(name,def);await teardowns[teardowns.length-1].ready}}return teardowns};
var runTest=async function(t,e){var ctx=new Ctx({id:t.id,timeoutMs:(e.timeout||CFG.timeouts.test)*(e.slow?3:1)});ctx.t=t;ctx.t.id=t.id;ctx.timeout=(e.timeout||CFG.timeouts.test)*(e.slow?3:1);ctx.deadline=ctx.started+ctx.timeout;ctx.expectFail=e.fail;CUR=ctx;post({tipo:"empieza",id:t.id});var started=now(),err=null,skipped=null;var fixtures=null,teardowns=[];
try{var vp=e.use.viewport||CFG.viewport;var r0=await ctx.cmd({op:"nueva-pagina",viewport:{width:Number(vp.width)||1280,height:Number(vp.height)||720}});if(!r0.ok)throw Fallo("No se ha podido preparar la página: "+r0.error,r0.error);
var page=new Page(ctx,e.use);ctx.page=page;fixtures={page:page,context:page.context(),browserName:"chromium",isMobile:!!e.use.isMobile,hasTouch:!!e.use.hasTouch,viewport:vp,baseURL:"http://localhost/",headless:true,request:new Proxy({},{get:function(){return NOSOP("request (peticiones de API)","prueba lo que se ve en la página")}}),browser:{newPage:NOSOP("browser.newPage()"),newContext:NOSOP("browser.newContext()"),version:function(){return "chromium"}}};
var info=TEST.info();
await withTimeout(ctx,async function(){if(t.fixtures.length)teardowns=await setupFixtures(t.fixtures,fixtures,info);var chain=chainOf(t.suite);for(var i=0;i<chain.length;i++){if(!chain[i].ranBeforeAll){chain[i].ranBeforeAll=true;for(var j=0;j<chain[i].hooks.beforeAll.length;j++)await chain[i].hooks.beforeAll[j](fixtures,info)}}
for(var a=0;a<chain.length;a++)for(var b=0;b<chain[a].hooks.beforeEach.length;b++)await chain[a].hooks.beforeEach[b](fixtures,info);await t.fn(fixtures,info)})}catch(x){if(x&&x.willy&&x.willy.saltada)skipped=x.willy.why||"skip";else err=x}
if(!(err&&err.willy&&err.willy.parado)){try{ctx.deadline=Math.max(ctx.deadline,now()+5000);var chain2=chainOf(t.suite);await withTimeout(ctx,async function(){for(var a=chain2.length-1;a>=0;a--)for(var b=0;b<chain2[a].hooks.afterEach.length;b++)await chain2[a].hooks.afterEach[b](fixtures,TEST.info());for(var d=teardowns.length-1;d>=0;d--)await teardowns[d].release()})}catch(x2){if(!err&&!skipped)err=x2}}
var ms=now()-started,res;if(skipped)res=RESULT(t,ctx,"saltada",null,ms);else{if(!err&&ctx.soft.length)err=ctx.soft[0];if(!err&&ctx.pageErrors.length)err=Fallo("La página dio un error de JavaScript: "+ctx.pageErrors[0],"Page error: "+ctx.pageErrors[0],null,{});
var failed=!!err;if(ctx.expectFail){res=failed?RESULT(t,ctx,"ok",null,ms):RESULT(t,ctx,"fallo",Fallo("Se esperaba que esta prueba fallara (test.fail) y ha salido bien.","Expected to fail, but passed."),ms)}else res=RESULT(t,ctx,failed?"fallo":"ok",err,ms);if(ctx.soft.length>1&&res.error)res.error.otros=ctx.soft.length-1}
ctx.gen++;if(ctx.aborted!=="parado")ctx.aborted="terminada";CUR=null;post({tipo:"termina",id:t.id,r:res});return res};
var runAll=async function(solo){try{await LOADED;var tests=[];var walk=function(s){s.items.forEach(function(it){if(it.fn)tests.push(it);else walk(it)})};ROOTS.forEach(walk);
var effs=tests.map(eff);var anyOnly=effs.some(function(e){return e.only});var list=[];tests.forEach(function(t,i){if(anyOnly&&!effs[i].only)return;if(solo&&solo.indexOf(t.id)<0)return;list.push({t:t,e:effs[i]})});
list.forEach(function(x){chainOf(x.t.suite).forEach(function(s){s.left++})});
for(var i=0;i<list.length;i++){var x=list[i];if(STOPPED){post({tipo:"termina",id:x.t.id,r:RESULT(x.t,null,"no-pasada",null,0)});continue}
if(x.e.skip){post({tipo:"termina",id:x.t.id,r:RESULT(x.t,null,"saltada",null,0)})}else await runTest(x.t,x.e);
var chain=chainOf(x.t.suite);for(var c=chain.length-1;c>=0;c--){chain[c].left--;if(chain[c].left===0&&chain[c].ranBeforeAll&&chain[c].hooks.afterAll.length&&!STOPPED){try{for(var h=0;h<chain[c].hooks.afterAll.length;h++)await chain[c].hooks.afterAll[h]({},TEST.info())}catch(e){}}}}}catch(err){post({tipo:"error",mensaje:String(err&&err.message||err)})}post({tipo:"fin"})};
var LOADED=loadFiles().then(function(){var tests=[];var walk=function(s){s.items.forEach(function(it){if(it.fn)tests.push({id:it.id,archivo:it.file,titulo:titlePath(it).join(" \u203a "),linea:(WHERE(it.site)||{}).linea||0});else walk(it)})};ROOTS.forEach(walk);post({tipo:"listo",pruebas:tests,errores:LOADERRS})},function(err){post({tipo:"listo",pruebas:[],errores:[{archivo:"",mensaje:String(err&&err.message||err),linea:0}]})});
`;

/** El documento del marco del pasador: sin red (CSP), con las pruebas del proyecto y la configuración de esta pasada. */
export function runnerDocument(token: string, files: RunnerFile[], config: RunnerConfig = DEFAULT_RUNNER_CONFIG): string {
  const k = token.replace(/[^\w.-]/g, "").slice(0, 60);
  const esc = (s: string) => s.replace(/</g, "\\u003c").replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029");
  const data = esc(JSON.stringify(files.map((f) => ({ path: f.path, code: f.code, lineMap: f.lineMap ?? null }))));
  const cfg = esc(JSON.stringify(config));
  return [
    "<!doctype html><html><head><meta charset=\"utf-8\">",
    // Sin red ni nada de fuera: las pruebas solo hablan con WILLY por mensajes.
    "<meta http-equiv=\"Content-Security-Policy\" content=\"default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'\">",
    `<script>(function(){\nvar K=${JSON.stringify(k)},CFG=${cfg},FILES=${data};\n${RUNNER}\n})();</script>`,
    "</head><body></body></html>",
  ].join("");
}

/** Lo que manda el pasador a WILLY (siempre con `__willyPruebas: true` y su marca). */
export type RunnerMessage =
  | { tipo: "listo"; pruebas: Array<{ id: string; archivo: string; titulo: string; linea: number }>; errores: Array<{ archivo: string; mensaje: string; linea: number }> }
  | { tipo: "orden"; id: number; cmd: Record<string, unknown> }
  | { tipo: "empieza"; id: string }
  | { tipo: "paso"; id: string; texto: string }
  | { tipo: "termina"; id: string; r: RawTestResult }
  | { tipo: "error"; mensaje: string }
  | { tipo: "fin" };

/** El resultado de una prueba tal como lo cuenta el pasador (se comprueba campo a campo en project-tests). */
export type RawTestResult = Record<string, unknown>;

export function asRunnerMessage(data: unknown, token: string): RunnerMessage | null {
  if (!data || typeof data !== "object") return null;
  const d = data as Record<string, unknown>;
  if (d["__willyPruebas"] !== true || d["k"] !== token || typeof d["tipo"] !== "string") return null;
  switch (d["tipo"]) {
    case "listo": {
      const pruebas = Array.isArray(d["pruebas"]) ? (d["pruebas"] as Array<Record<string, unknown>>).slice(0, 500).map((p) => ({ id: String(p["id"] ?? "").slice(0, 400), archivo: String(p["archivo"] ?? "").slice(0, 300), titulo: String(p["titulo"] ?? "").slice(0, 300), linea: Number(p["linea"]) || 0 })) : [];
      const errores = Array.isArray(d["errores"]) ? (d["errores"] as Array<Record<string, unknown>>).slice(0, 50).map((e) => ({ archivo: String(e["archivo"] ?? "").slice(0, 300), mensaje: String(e["mensaje"] ?? "").slice(0, 500), linea: Number(e["linea"]) || 0 })) : [];
      return { tipo: "listo", pruebas, errores };
    }
    case "orden": {
      const id = Number(d["id"]);
      const cmd = d["cmd"] && typeof d["cmd"] === "object" ? (d["cmd"] as Record<string, unknown>) : null;
      return Number.isFinite(id) && cmd ? { tipo: "orden", id, cmd } : null;
    }
    case "empieza": return { tipo: "empieza", id: String(d["id"] ?? "") };
    case "paso": return { tipo: "paso", id: String(d["id"] ?? ""), texto: String(d["texto"] ?? "").slice(0, 200) };
    case "termina": return { tipo: "termina", id: String(d["id"] ?? ""), r: d["r"] && typeof d["r"] === "object" ? (d["r"] as RawTestResult) : {} };
    case "error": return { tipo: "error", mensaje: String(d["mensaje"] ?? "").slice(0, 500) };
    case "fin": return { tipo: "fin" };
    default: return null;
  }
}
