/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as DescargarRouteImport } from './routes/descargar'
import { Route as ApiBuildInstallerRouteImport } from './routes/api/build-installer'
import { Route as ApiEngineRouteImport } from './routes/api/engine'
import { Route as ApiFetchUrlRouteImport } from './routes/api/fetch-url'
import { Route as ApiLocalAiRouteImport } from './routes/api/local-ai'
import { Route as ApiTtsRouteImport } from './routes/api/tts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DescargarRoute = DescargarRouteImport.update({
  id: '/descargar',
  path: '/descargar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildInstallerRoute = ApiBuildInstallerRouteImport.update({
  id: '/api/build-installer',
  path: '/api/build-installer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEngineRoute = ApiEngineRouteImport.update({
  id: '/api/engine',
  path: '/api/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFetchUrlRoute = ApiFetchUrlRouteImport.update({
  id: '/api/fetch-url',
  path: '/api/fetch-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocalAiRoute = ApiLocalAiRouteImport.update({
  id: '/api/local-ai',
  path: '/api/local-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/descargar': typeof DescargarRoute
  '/api/build-installer': typeof ApiBuildInstallerRoute
  '/api/engine': typeof ApiEngineRoute
  '/api/fetch-url': typeof ApiFetchUrlRoute
  '/api/local-ai': typeof ApiLocalAiRoute
  '/api/tts': typeof ApiTtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/descargar': typeof DescargarRoute
  '/api/build-installer': typeof ApiBuildInstallerRoute
  '/api/engine': typeof ApiEngineRoute
  '/api/fetch-url': typeof ApiFetchUrlRoute
  '/api/local-ai': typeof ApiLocalAiRoute
  '/api/tts': typeof ApiTtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/descargar': typeof DescargarRoute
  '/api/build-installer': typeof ApiBuildInstallerRoute
  '/api/engine': typeof ApiEngineRoute
  '/api/fetch-url': typeof ApiFetchUrlRoute
  '/api/local-ai': typeof ApiLocalAiRoute
  '/api/tts': typeof ApiTtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/descargar'
    | '/api/build-installer'
    | '/api/engine'
    | '/api/fetch-url'
    | '/api/local-ai'
    | '/api/tts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/descargar'
    | '/api/build-installer'
    | '/api/engine'
    | '/api/fetch-url'
    | '/api/local-ai'
    | '/api/tts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/descargar'
    | '/api/build-installer'
    | '/api/engine'
    | '/api/fetch-url'
    | '/api/local-ai'
    | '/api/tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  DescargarRoute: typeof DescargarRoute
  ApiBuildInstallerRoute: typeof ApiBuildInstallerRoute
  ApiEngineRoute: typeof ApiEngineRoute
  ApiFetchUrlRoute: typeof ApiFetchUrlRoute
  ApiLocalAiRoute: typeof ApiLocalAiRoute
  ApiTtsRoute: typeof ApiTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descargar': {
      id: '/descargar'
      path: '/descargar'
      fullPath: '/descargar'
      preLoaderRoute: typeof DescargarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/build-installer': {
      id: '/api/build-installer'
      path: '/api/build-installer'
      fullPath: '/api/build-installer'
      preLoaderRoute: typeof ApiBuildInstallerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/engine': {
      id: '/api/engine'
      path: '/api/engine'
      fullPath: '/api/engine'
      preLoaderRoute: typeof ApiEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fetch-url': {
      id: '/api/fetch-url'
      path: '/api/fetch-url'
      fullPath: '/api/fetch-url'
      preLoaderRoute: typeof ApiFetchUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/local-ai': {
      id: '/api/local-ai'
      path: '/api/local-ai'
      fullPath: '/api/local-ai'
      preLoaderRoute: typeof ApiLocalAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  DescargarRoute: DescargarRoute,
  ApiBuildInstallerRoute: ApiBuildInstallerRoute,
  ApiEngineRoute: ApiEngineRoute,
  ApiFetchUrlRoute: ApiFetchUrlRoute,
  ApiLocalAiRoute: ApiLocalAiRoute,
  ApiTtsRoute: ApiTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
