/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as DescargarRouteImport } from './routes/descargar'
import { Route as MovilRouteImport } from './routes/movil'
import { Route as ApiActualizacionRouteImport } from './routes/api/actualizacion'
import { Route as ApiAvatarRouteImport } from './routes/api/avatar'
import { Route as ApiBuildInstallerRouteImport } from './routes/api/build-installer'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiEngineRouteImport } from './routes/api/engine'
import { Route as ApiFabricaRouteImport } from './routes/api/fabrica'
import { Route as ApiFetchUrlRouteImport } from './routes/api/fetch-url'
import { Route as ApiIphoneRouteImport } from './routes/api/iphone'
import { Route as ApiJuridicoRouteImport } from './routes/api/juridico'
import { Route as ApiLanRouteImport } from './routes/api/lan'
import { Route as ApiLocalAiRouteImport } from './routes/api/local-ai'
import { Route as ApiProyectosRouteImport } from './routes/api/proyectos'
import { Route as ApiRemoteAccessRouteImport } from './routes/api/remote-access'
import { Route as ApiRemoteStatusRouteImport } from './routes/api/remote-status'
import { Route as ApiSelfAuditRouteImport } from './routes/api/self-audit'
import { Route as ApiSelfBuildRouteImport } from './routes/api/self-build'
import { Route as ApiSistemaRouteImport } from './routes/api/sistema'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiVocesRouteImport } from './routes/api/voces'
import { Route as ApiYoutubeRouteImport } from './routes/api/youtube'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DescargarRoute = DescargarRouteImport.update({
  id: '/descargar',
  path: '/descargar',
  getParentRoute: () => rootRouteImport,
} as any)
const MovilRoute = MovilRouteImport.update({
  id: '/movil',
  path: '/movil',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActualizacionRoute = ApiActualizacionRouteImport.update({
  id: '/api/actualizacion',
  path: '/api/actualizacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarRoute = ApiAvatarRouteImport.update({
  id: '/api/avatar',
  path: '/api/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildInstallerRoute = ApiBuildInstallerRouteImport.update({
  id: '/api/build-installer',
  path: '/api/build-installer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEngineRoute = ApiEngineRouteImport.update({
  id: '/api/engine',
  path: '/api/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFabricaRoute = ApiFabricaRouteImport.update({
  id: '/api/fabrica',
  path: '/api/fabrica',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFetchUrlRoute = ApiFetchUrlRouteImport.update({
  id: '/api/fetch-url',
  path: '/api/fetch-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIphoneRoute = ApiIphoneRouteImport.update({
  id: '/api/iphone',
  path: '/api/iphone',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJuridicoRoute = ApiJuridicoRouteImport.update({
  id: '/api/juridico',
  path: '/api/juridico',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLanRoute = ApiLanRouteImport.update({
  id: '/api/lan',
  path: '/api/lan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocalAiRoute = ApiLocalAiRouteImport.update({
  id: '/api/local-ai',
  path: '/api/local-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProyectosRoute = ApiProyectosRouteImport.update({
  id: '/api/proyectos',
  path: '/api/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemoteAccessRoute = ApiRemoteAccessRouteImport.update({
  id: '/api/remote-access',
  path: '/api/remote-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemoteStatusRoute = ApiRemoteStatusRouteImport.update({
  id: '/api/remote-status',
  path: '/api/remote-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSelfAuditRoute = ApiSelfAuditRouteImport.update({
  id: '/api/self-audit',
  path: '/api/self-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSelfBuildRoute = ApiSelfBuildRouteImport.update({
  id: '/api/self-build',
  path: '/api/self-build',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSistemaRoute = ApiSistemaRouteImport.update({
  id: '/api/sistema',
  path: '/api/sistema',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVocesRoute = ApiVocesRouteImport.update({
  id: '/api/voces',
  path: '/api/voces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeRoute = ApiYoutubeRouteImport.update({
  id: '/api/youtube',
  path: '/api/youtube',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/descargar': typeof DescargarRoute
  '/movil': typeof MovilRoute
  '/api/actualizacion': typeof ApiActualizacionRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/build-installer': typeof ApiBuildInstallerRoute
  '/api/chat': typeof ApiChatRoute
  '/api/engine': typeof ApiEngineRoute
  '/api/fabrica': typeof ApiFabricaRoute
  '/api/fetch-url': typeof ApiFetchUrlRoute
  '/api/iphone': typeof ApiIphoneRoute
  '/api/juridico': typeof ApiJuridicoRoute
  '/api/lan': typeof ApiLanRoute
  '/api/local-ai': typeof ApiLocalAiRoute
  '/api/proyectos': typeof ApiProyectosRoute
  '/api/remote-access': typeof ApiRemoteAccessRoute
  '/api/remote-status': typeof ApiRemoteStatusRoute
  '/api/self-audit': typeof ApiSelfAuditRoute
  '/api/self-build': typeof ApiSelfBuildRoute
  '/api/sistema': typeof ApiSistemaRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/voces': typeof ApiVocesRoute
  '/api/youtube': typeof ApiYoutubeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/descargar': typeof DescargarRoute
  '/movil': typeof MovilRoute
  '/api/actualizacion': typeof ApiActualizacionRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/build-installer': typeof ApiBuildInstallerRoute
  '/api/chat': typeof ApiChatRoute
  '/api/engine': typeof ApiEngineRoute
  '/api/fabrica': typeof ApiFabricaRoute
  '/api/fetch-url': typeof ApiFetchUrlRoute
  '/api/iphone': typeof ApiIphoneRoute
  '/api/juridico': typeof ApiJuridicoRoute
  '/api/lan': typeof ApiLanRoute
  '/api/local-ai': typeof ApiLocalAiRoute
  '/api/proyectos': typeof ApiProyectosRoute
  '/api/remote-access': typeof ApiRemoteAccessRoute
  '/api/remote-status': typeof ApiRemoteStatusRoute
  '/api/self-audit': typeof ApiSelfAuditRoute
  '/api/self-build': typeof ApiSelfBuildRoute
  '/api/sistema': typeof ApiSistemaRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/voces': typeof ApiVocesRoute
  '/api/youtube': typeof ApiYoutubeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/descargar': typeof DescargarRoute
  '/movil': typeof MovilRoute
  '/api/actualizacion': typeof ApiActualizacionRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/build-installer': typeof ApiBuildInstallerRoute
  '/api/chat': typeof ApiChatRoute
  '/api/engine': typeof ApiEngineRoute
  '/api/fabrica': typeof ApiFabricaRoute
  '/api/fetch-url': typeof ApiFetchUrlRoute
  '/api/iphone': typeof ApiIphoneRoute
  '/api/juridico': typeof ApiJuridicoRoute
  '/api/lan': typeof ApiLanRoute
  '/api/local-ai': typeof ApiLocalAiRoute
  '/api/proyectos': typeof ApiProyectosRoute
  '/api/remote-access': typeof ApiRemoteAccessRoute
  '/api/remote-status': typeof ApiRemoteStatusRoute
  '/api/self-audit': typeof ApiSelfAuditRoute
  '/api/self-build': typeof ApiSelfBuildRoute
  '/api/sistema': typeof ApiSistemaRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/voces': typeof ApiVocesRoute
  '/api/youtube': typeof ApiYoutubeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/descargar'
    | '/movil'
    | '/api/actualizacion'
    | '/api/avatar'
    | '/api/build-installer'
    | '/api/chat'
    | '/api/engine'
    | '/api/fabrica'
    | '/api/fetch-url'
    | '/api/iphone'
    | '/api/juridico'
    | '/api/lan'
    | '/api/local-ai'
    | '/api/proyectos'
    | '/api/remote-access'
    | '/api/remote-status'
    | '/api/self-audit'
    | '/api/self-build'
    | '/api/sistema'
    | '/api/tts'
    | '/api/voces'
    | '/api/youtube'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/descargar'
    | '/movil'
    | '/api/actualizacion'
    | '/api/avatar'
    | '/api/build-installer'
    | '/api/chat'
    | '/api/engine'
    | '/api/fabrica'
    | '/api/fetch-url'
    | '/api/iphone'
    | '/api/juridico'
    | '/api/lan'
    | '/api/local-ai'
    | '/api/proyectos'
    | '/api/remote-access'
    | '/api/remote-status'
    | '/api/self-audit'
    | '/api/self-build'
    | '/api/sistema'
    | '/api/tts'
    | '/api/voces'
    | '/api/youtube'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/descargar'
    | '/movil'
    | '/api/actualizacion'
    | '/api/avatar'
    | '/api/build-installer'
    | '/api/chat'
    | '/api/engine'
    | '/api/fabrica'
    | '/api/fetch-url'
    | '/api/iphone'
    | '/api/juridico'
    | '/api/lan'
    | '/api/local-ai'
    | '/api/proyectos'
    | '/api/remote-access'
    | '/api/remote-status'
    | '/api/self-audit'
    | '/api/self-build'
    | '/api/sistema'
    | '/api/tts'
    | '/api/voces'
    | '/api/youtube'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  DescargarRoute: typeof DescargarRoute
  MovilRoute: typeof MovilRoute
  ApiActualizacionRoute: typeof ApiActualizacionRoute
  ApiAvatarRoute: typeof ApiAvatarRoute
  ApiBuildInstallerRoute: typeof ApiBuildInstallerRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiEngineRoute: typeof ApiEngineRoute
  ApiFabricaRoute: typeof ApiFabricaRoute
  ApiFetchUrlRoute: typeof ApiFetchUrlRoute
  ApiIphoneRoute: typeof ApiIphoneRoute
  ApiJuridicoRoute: typeof ApiJuridicoRoute
  ApiLanRoute: typeof ApiLanRoute
  ApiLocalAiRoute: typeof ApiLocalAiRoute
  ApiProyectosRoute: typeof ApiProyectosRoute
  ApiRemoteAccessRoute: typeof ApiRemoteAccessRoute
  ApiRemoteStatusRoute: typeof ApiRemoteStatusRoute
  ApiSelfAuditRoute: typeof ApiSelfAuditRoute
  ApiSelfBuildRoute: typeof ApiSelfBuildRoute
  ApiSistemaRoute: typeof ApiSistemaRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiVocesRoute: typeof ApiVocesRoute
  ApiYoutubeRoute: typeof ApiYoutubeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descargar': {
      id: '/descargar'
      path: '/descargar'
      fullPath: '/descargar'
      preLoaderRoute: typeof DescargarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movil': {
      id: '/movil'
      path: '/movil'
      fullPath: '/movil'
      preLoaderRoute: typeof MovilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/actualizacion': {
      id: '/api/actualizacion'
      path: '/api/actualizacion'
      fullPath: '/api/actualizacion'
      preLoaderRoute: typeof ApiActualizacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatar': {
      id: '/api/avatar'
      path: '/api/avatar'
      fullPath: '/api/avatar'
      preLoaderRoute: typeof ApiAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/build-installer': {
      id: '/api/build-installer'
      path: '/api/build-installer'
      fullPath: '/api/build-installer'
      preLoaderRoute: typeof ApiBuildInstallerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/engine': {
      id: '/api/engine'
      path: '/api/engine'
      fullPath: '/api/engine'
      preLoaderRoute: typeof ApiEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fabrica': {
      id: '/api/fabrica'
      path: '/api/fabrica'
      fullPath: '/api/fabrica'
      preLoaderRoute: typeof ApiFabricaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fetch-url': {
      id: '/api/fetch-url'
      path: '/api/fetch-url'
      fullPath: '/api/fetch-url'
      preLoaderRoute: typeof ApiFetchUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/iphone': {
      id: '/api/iphone'
      path: '/api/iphone'
      fullPath: '/api/iphone'
      preLoaderRoute: typeof ApiIphoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/juridico': {
      id: '/api/juridico'
      path: '/api/juridico'
      fullPath: '/api/juridico'
      preLoaderRoute: typeof ApiJuridicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lan': {
      id: '/api/lan'
      path: '/api/lan'
      fullPath: '/api/lan'
      preLoaderRoute: typeof ApiLanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/local-ai': {
      id: '/api/local-ai'
      path: '/api/local-ai'
      fullPath: '/api/local-ai'
      preLoaderRoute: typeof ApiLocalAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proyectos': {
      id: '/api/proyectos'
      path: '/api/proyectos'
      fullPath: '/api/proyectos'
      preLoaderRoute: typeof ApiProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remote-access': {
      id: '/api/remote-access'
      path: '/api/remote-access'
      fullPath: '/api/remote-access'
      preLoaderRoute: typeof ApiRemoteAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remote-status': {
      id: '/api/remote-status'
      path: '/api/remote-status'
      fullPath: '/api/remote-status'
      preLoaderRoute: typeof ApiRemoteStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/self-audit': {
      id: '/api/self-audit'
      path: '/api/self-audit'
      fullPath: '/api/self-audit'
      preLoaderRoute: typeof ApiSelfAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/self-build': {
      id: '/api/self-build'
      path: '/api/self-build'
      fullPath: '/api/self-build'
      preLoaderRoute: typeof ApiSelfBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sistema': {
      id: '/api/sistema'
      path: '/api/sistema'
      fullPath: '/api/sistema'
      preLoaderRoute: typeof ApiSistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voces': {
      id: '/api/voces'
      path: '/api/voces'
      fullPath: '/api/voces'
      preLoaderRoute: typeof ApiVocesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube': {
      id: '/api/youtube'
      path: '/api/youtube'
      fullPath: '/api/youtube'
      preLoaderRoute: typeof ApiYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  DescargarRoute: DescargarRoute,
  MovilRoute: MovilRoute,
  ApiActualizacionRoute: ApiActualizacionRoute,
  ApiAvatarRoute: ApiAvatarRoute,
  ApiBuildInstallerRoute: ApiBuildInstallerRoute,
  ApiChatRoute: ApiChatRoute,
  ApiEngineRoute: ApiEngineRoute,
  ApiFabricaRoute: ApiFabricaRoute,
  ApiFetchUrlRoute: ApiFetchUrlRoute,
  ApiIphoneRoute: ApiIphoneRoute,
  ApiJuridicoRoute: ApiJuridicoRoute,
  ApiLanRoute: ApiLanRoute,
  ApiLocalAiRoute: ApiLocalAiRoute,
  ApiProyectosRoute: ApiProyectosRoute,
  ApiRemoteAccessRoute: ApiRemoteAccessRoute,
  ApiRemoteStatusRoute: ApiRemoteStatusRoute,
  ApiSelfAuditRoute: ApiSelfAuditRoute,
  ApiSelfBuildRoute: ApiSelfBuildRoute,
  ApiSistemaRoute: ApiSistemaRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiVocesRoute: ApiVocesRoute,
  ApiYoutubeRoute: ApiYoutubeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
